import { chmodSync, readFileSync, writeFileSync } from "node:fs";
import { spawnSync } from "node:child_process";
import { randomBytes } from "node:crypto";
import { PrismaClient } from "@prisma/client";
import { TenantAccessBroker } from "../src/lib/tenant-access-broker";
import { TenantBoundPrismaCredentialAuthority, TenantBoundPrismaExecutor, type TenantConnectionProvider } from "../src/lib/tenant-bound-prisma-authority";
import { W02SecurityRepository } from "../src/lib/w02-security-repository";
import { decidePrivacyAction, opaqueSecretReference } from "../src/lib/w02-security-contracts";
import type { TenantContext } from "../src/lib/tenant-context";

const suffix = `${Date.now()}_${process.pid}`;
const database = `asas_w02_internal_${suffix}`;
const roles = { migrator: `w02_int_migrator_${suffix}`, control: `w02_int_control_${suffix}`, a: `w02_int_a_${suffix}`, b: `w02_int_b_${suffix}`, none: `w02_int_none_${suffix}` };
const passwords = Object.fromEntries(Object.keys(roles).map((key) => [key, randomBytes(30).toString("base64url")])) as Record<keyof typeof roles, string>;
const evidenceFile = `/tmp/w02-internal-security-evidence-${suffix}.json`;
const mandatoryIds = ["INT01", "INT02", "INT03", "INT04", "INT05", "INT06", "INT07", "INT08", "INT09", "INT10", "INT11", "INT12", "INT13", "INT14"];
const orgA = "33333333-3333-4333-8333-333333333333"; const orgB = "44444444-4444-4444-8444-444444444444";
const userA = "cccccccc-0000-4000-8000-000000000001"; const userB = "dddddddd-0000-4000-8000-000000000002";
const membershipA = "cccccccc-0000-4000-8000-000000000101"; const membershipB = "dddddddd-0000-4000-8000-000000000102";
const evidence: Array<Record<string, unknown>> = [];

function run(command: string, args: string[], options: Record<string, unknown> = {}) { return spawnSync(command, args, { encoding: "utf8", ...options }); }
function sql(statement: string, db = "postgres") { const result = run("sudo", ["-u", "postgres", "psql", "-d", db, "-X", "-v", "ON_ERROR_STOP=1", "-At"], { input: statement }); if (result.status !== 0) throw new Error("AUDIT_ADMIN_SQL_FAILED"); return result.stdout.trim(); }
function url(key: keyof typeof roles) { return `postgresql://${roles[key]}:${passwords[key]}@127.0.0.1:5432/${database}?schema=public`; }
function write(payload: Record<string, unknown>) { writeFileSync(evidenceFile, `${JSON.stringify(payload, null, 2)}\n`, { mode: 0o600 }); chmodSync(evidenceFile, 0o600); }
function context(organizationId: string, userId: string, membershipId: string, correlationId: string): TenantContext { return Object.freeze({ organizationId, userId, membershipId, correlationId, sessionVersion: 1, policySnapshotVersion: 1 }); }
async function record(id: string, expected: string, action: () => Promise<boolean>) { try { const actual = await action(); evidence.push({ id, expected, actual, result: actual ? "PASS" : "FAIL", cleanupStatus: "PENDING" }); } catch { evidence.push({ id, expected, actual: "REDACTED_EXCEPTION", result: "FAIL", cleanupStatus: "PENDING" }); } }
async function denied(action: () => Promise<unknown>) { try { await action(); return false; } catch { return true; } }
function cleanup() { const all = Object.values(roles); const errors: string[] = []; try { sql(`SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname='${database}' AND pid <> pg_backend_pid();`); } catch { errors.push("TERMINATE_FAILED"); } try { sql(`DROP DATABASE IF EXISTS ${database} WITH (FORCE);`); } catch { errors.push("DROP_DATABASE_FAILED"); } for (const role of all) try { sql(`DROP ROLE IF EXISTS ${role};`); } catch { errors.push("DROP_ROLE_FAILED"); } let residue = ""; try { residue = sql(`SELECT datname FROM pg_database WHERE datname='${database}' UNION ALL SELECT rolname FROM pg_roles WHERE rolname IN (${all.map((role) => `'${role}'`).join(",")});`); } catch { errors.push("RESIDUE_SCAN_FAILED"); } return { ok: errors.length === 0 && residue === "", errors, residueCount: residue ? residue.split("\n").filter(Boolean).length : 0 }; }

async function main() {
  const startedAt = new Date().toISOString(); let phase = "bootstrap"; let control: PrismaClient | null = null; let directA: PrismaClient | null = null; let directB: PrismaClient | null = null; let directNone: PrismaClient | null = null;
  try {
    sql(`CREATE ROLE ${roles.migrator} LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS PASSWORD '${passwords.migrator}'; CREATE DATABASE ${database} OWNER ${roles.migrator}; CREATE ROLE ${roles.control} LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS PASSWORD '${passwords.control}'; CREATE ROLE ${roles.a} LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS PASSWORD '${passwords.a}'; CREATE ROLE ${roles.b} LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS PASSWORD '${passwords.b}'; CREATE ROLE ${roles.none} LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS PASSWORD '${passwords.none}';`);
    phase = "migration"; if (run("./node_modules/.bin/prisma", ["migrate", "deploy", "--schema", "prisma/schema.prisma"], { env: { ...process.env, DATABASE_URL: url("migrator") } }).status !== 0) throw new Error("MIGRATION_DEPLOY_FAILED");
    const tenants = `${roles.a}, ${roles.b}, ${roles.none}`;
    phase = "grant-seed"; sql(`GRANT CONNECT ON DATABASE ${database} TO ${roles.control}, ${tenants}; GRANT USAGE ON SCHEMA public, security TO ${roles.control}, ${tenants}; GRANT EXECUTE ON FUNCTION security.current_session_organization_id() TO ${tenants}; GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "organizations", "users", "organization_memberships", "tenant_database_principals", "tenant_access_leases", "tenant_broker_audit_events" TO ${roles.control}; GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "secret_records", "secret_access_audits", "privacy_policy_bindings", "privacy_requests", "activation_records", "identity_provider_configs", "identity_subject_bindings", "identity_provider_callback_states" TO ${tenants};`, database);
    sql(`INSERT INTO "organizations" ("id","name","createdAt","updatedAt") VALUES ('${orgA}','Organization A',now(),now()),('${orgB}','Organization B',now(),now()); INSERT INTO "users" ("id","name","email","role","isActive","authVersion","activeOrganizationId","createdAt","updatedAt") VALUES ('${userA}','A','a-${suffix}@audit.invalid','MEMBER',true,1,'${orgA}',now(),now()),('${userB}','B','b-${suffix}@audit.invalid','MEMBER',true,1,'${orgB}',now(),now()); INSERT INTO "organization_memberships" ("id","organizationId","userId","role","isActive","policyVersion","createdAt","updatedAt") VALUES ('${membershipA}','${orgA}','${userA}','MEMBER',true,1,now(),now()),('${membershipB}','${orgB}','${userB}','MEMBER',true,1,now(),now()); INSERT INTO security.role_to_organization (role_oid, organization_id) VALUES ('${roles.a}'::regrole::oid,'${orgA}'),('${roles.b}'::regrole::oid,'${orgB}'); INSERT INTO "tenant_database_principals" ("id","organizationId","principalName","credentialReference","generation","status","activatedAt","createdAt","updatedAt") VALUES ('principal-a','${orgA}','${roles.a}','audit://w02-internal/a',1,'ACTIVE',now(),now(),now()),('principal-b','${orgB}','${roles.b}','audit://w02-internal/b',1,'ACTIVE',now(),now(),now());`, database);
    sql(`INSERT INTO "secret_records" ("id","organizationId","providerKey","purpose","opaqueReference","keyVersion","createdById","createdAt","updatedAt") VALUES ('secret-a','${orgA}','idp','callback','secretref:audit-ref-0001','v1','${userA}',now(),now()),('secret-b','${orgB}','idp','callback','secretref:audit-ref-0002','v1','${userB}',now(),now()); INSERT INTO "privacy_policy_bindings" ("id","organizationId","recordType","classification","isApproved","createdAt","updatedAt") VALUES ('policy-a','${orgA}','Beneficiary','RESTRICTED',false,now(),now()),('policy-b','${orgB}','Beneficiary','RESTRICTED',true,now(),now()); INSERT INTO "identity_provider_configs" ("id","organizationId","providerKey","environment","status","createdAt","updatedAt") VALUES ('idp-a','${orgA}','fixture','SANDBOX','DISABLED',now(),now()),('idp-b','${orgB}','fixture','SANDBOX','DISABLED',now(),now());`, database);
    control = new PrismaClient({ datasources: { db: { url: url("control") } } }); directA = new PrismaClient({ datasources: { db: { url: url("a") } } }); directB = new PrismaClient({ datasources: { db: { url: url("b") } } }); directNone = new PrismaClient({ datasources: { db: { url: url("none") } } });
    const entries = new Map([["audit://w02-internal/a", { role: roles.a, url: url("a") }], ["audit://w02-internal/b", { role: roles.b, url: url("b") }]]); const unavailable = new Set<string>(); let checkoutCount = 0; let discardCount = 0;
    const provider: TenantConnectionProvider = { async checkout(input) { const entry = entries.get(input.credentialReference); if (!entry || unavailable.has(input.credentialReference) || entry.role !== input.principalName) throw new Error("PROVIDER_UNAVAILABLE"); const prisma = new PrismaClient({ datasources: { db: { url: entry.url } } }); const identity = await prisma.$queryRawUnsafe<Array<{ session_user: string }>>("SELECT session_user"); if (identity[0]?.session_user !== input.principalName) { await prisma.$disconnect(); throw new Error("SESSION_USER_MISMATCH"); } checkoutCount += 1; return { prisma, discard: async () => { discardCount += 1; await prisma.$disconnect(); } }; } };
    const executor = new TenantBoundPrismaExecutor(new TenantAccessBroker(control, new TenantBoundPrismaCredentialAuthority(provider), 5_000)); const repo = new W02SecurityRepository(executor); const ctxA = context(orgA, userA, membershipA, "w02-internal-a"); const ctxB = context(orgB, userB, membershipB, "w02-internal-b"); const identity = (db: PrismaClient) => db.$queryRawUnsafe<Array<{ session_user: string }>>("SELECT session_user").then((rows) => rows[0]?.session_user);
    await record("INT01", "migration deploys all seven FORCE RLS tenant tables and tenant roles lack bypass", async () => sql("SELECT count(*) FROM _prisma_migrations WHERE migration_name='20260824100000_w02_internal_security_contracts' AND finished_at IS NOT NULL", database) === "1" && sql("SELECT count(*) FROM pg_class WHERE relname IN ('secret_records','secret_access_audits','privacy_policy_bindings','privacy_requests','activation_records','identity_provider_configs','identity_subject_bindings','identity_provider_callback_states') AND relrowsecurity AND relforcerowsecurity", database) === "8" && sql(`SELECT count(*) FROM pg_roles WHERE rolname IN ('${roles.a}','${roles.b}','${roles.none}') AND (rolsuper OR rolbypassrls)`, database) === "0");
    await record("INT02", "secret references are isolated A/B and cross-tenant writes are denied", async () => (await directA!.secretRecord.count()) === 1 && (await directB!.secretRecord.count()) === 1 && (await directA!.secretRecord.findUnique({ where: { id: "secret-b" } })) === null && await denied(() => directA!.secretRecord.create({ data: { organizationId: orgB, providerKey: "bad", purpose: "bad", opaqueReference: "secretref:cross-tenant-0001", keyVersion: "v1", createdById: userA } })));
    await record("INT03", "privacy policy/request reads and no-map role fail closed", async () => (await directA!.privacyPolicyBinding.count()) === 1 && (await directB!.privacyPolicyBinding.count()) === 1 && (await directNone!.privacyRequest.count()) === 0 && await denied(() => directA!.privacyRequest.create({ data: { organizationId: orgB, requesterId: userA, type: "EXPORT", recordType: "Beneficiary", classification: "RESTRICTED", purposeCode: "DSAR" } })));
    await record("INT04", "activation and IdP roots are isolated by session_user", async () => await directA!.activationRecord.create({ data: { organizationId: orgA, licenseKeyId: "lic-a", instanceId: "instance-a", certificateFingerprint: "fp-a", activationCodeHash: "hash-a", activationCodeSalt: "salt-a", expiresAt: new Date(Date.now() + 60_000), createdById: userA, correlationId: "int04" } }).then(() => directB!.activationRecord.count()).then((count) => count === 0));
    await record("INT05", "foreign IdP config child writes are denied", async () => await denied(() => directA!.identitySubjectBinding.create({ data: { organizationId: orgA, identityProviderConfigId: "idp-b", membershipId: membershipA, subjectHash: "subject-hash" } })) && await denied(() => directA!.identityProviderCallbackState.create({ data: { organizationId: orgA, identityProviderConfigId: "idp-b", membershipId: membershipA, stateHash: "state-hash-a", expiresAt: new Date(Date.now() + 60_000) } })));
    await record("INT06", "SET ROLE cannot switch session identity", async () => await denied(() => directA!.$executeRawUnsafe(`SET ROLE ${roles.b}`)) && await identity(directA!) === roles.a);
    await record("INT07", "Broker executor exposes expected session_user and repository stamps org A/B", async () => { const [a, b] = await Promise.all([executor.execute(ctxA, identity), executor.execute(ctxB, identity)]); const [sa, sb] = await Promise.all([repo.createSecretReference(ctxA, { providerKey: "runtime", purpose: "rotate", opaqueReference: opaqueSecretReference("secretref:runtime-a-0001"), keyVersion: "v1" }), repo.createSecretReference(ctxB, { providerKey: "runtime", purpose: "rotate", opaqueReference: opaqueSecretReference("secretref:runtime-b-0001"), keyVersion: "v1" })]); return a === roles.a && b === roles.b && sa.organizationId === orgA && sb.organizationId === orgB && discardCount >= checkoutCount; });
    await record("INT08", "repository rejects foreign secret revoke and audit remains tenant scoped", async () => await denied(() => repo.revokeSecretReference(ctxA, "secret-b", "callback")) && (await directA!.secretAccessAudit.count()) === 0);
    await record("INT09", "privacy contract remains default-deny and legal hold overrides approved policy", async () => decidePrivacyAction({ policyApproved: false, legalHold: false }).code === "POLICY_REQUIRED" && decidePrivacyAction({ policyApproved: true, legalHold: true }).code === "LEGAL_HOLD");
    await record("INT10", "activation state rejects expired/replayed/revoked state before acceptance", async () => { const expired = await directA!.activationRecord.create({ data: { organizationId: orgA, licenseKeyId: "lic-expired", instanceId: "instance-expired", certificateFingerprint: "fp", activationCodeHash: "hash", activationCodeSalt: "salt", expiresAt: new Date(Date.now() - 60_000), createdById: userA, correlationId: "int10" } }); return await denied(() => repo.recordActivationAttempt(ctxA, expired.id, true)); });
    await record("INT11", "membership mismatch prevents IdP subject binding", async () => await denied(() => repo.bindIdentitySubject(ctxA, { configId: "idp-a", membershipId: membershipB, subjectHash: "foreign-member" })));
    await record("INT12", "provider outage fails closed and no global fallback occurs", async () => { unavailable.add("audit://w02-internal/a"); const outage = await denied(() => repo.createSecretReference(ctxA, { providerKey: "outage", purpose: "read", opaqueReference: opaqueSecretReference("secretref:outage-a-0001"), keyVersion: "v1" })); unavailable.delete("audit://w02-internal/a"); return outage; });
    await record("INT13", "parallel A/B operations discard every checkout and source forbids unsafe authority", async () => { const [a, b] = await Promise.all([repo.requestPrivacyAction(ctxA, { type: "EXPORT", recordType: "Beneficiary", classification: "RESTRICTED", purposeCode: "DSAR" }), repo.requestPrivacyAction(ctxB, { type: "ACCESS", recordType: "Beneficiary", classification: "RESTRICTED", purposeCode: "DSAR" })]); const source = readFileSync("src/lib/w02-security-repository.ts", "utf8"); return a.organizationId === orgA && b.organizationId === orgB && discardCount >= checkoutCount && !/(from "@\/lib\/db"|current_setting|set_config|DATABASE_URL|activeOrganizationId|organizationMemberships\[0\])/.test(source); });
    await record("INT14", "mandatory IDs are unique and all previous gates recorded", async () => { const observed = evidence.map((item) => item.id); return new Set(mandatoryIds).size === mandatoryIds.length && mandatoryIds.slice(0, -1).every((id) => observed.includes(id)) && new Set(observed).size === observed.length; });
    await Promise.all([control.$disconnect(), directA.$disconnect(), directB.$disconnect(), directNone.$disconnect()]); control = directA = directB = directNone = null; const finalCleanup = cleanup(); for (const item of evidence) item.cleanupStatus = finalCleanup.ok ? "PASS" : "FAIL"; const hygiene = run("node", ["scripts/w02-audit-artifact-hygiene-scan.mjs"]).status === 0; const failed = evidence.filter((item) => item.result !== "PASS").map((item) => item.id); const payload = { status: finalCleanup.ok && hygiene && failed.length === 0 && evidence.length === mandatoryIds.length ? "PASS_W02_INTERNAL_SECURITY_RUNTIME" : finalCleanup.ok ? "FAIL" : "FAIL_CLEANUP", startedAt, finishedAt: new Date().toISOString(), environment: "disposable-postgresql-audit", databaseAlias: database, mandatoryIds, evidence, hardFailures: failed, cleanup: finalCleanup, hygiene: { status: hygiene ? "PASS" : "FAIL" }, credentialsPersisted: false, productionResourcesTouched: false, rawGucIdentityUsed: false, globalPrismaFallback: false, ownerOrBypassUsedForTenantEvidence: false }; write(payload); process.stdout.write(`${JSON.stringify({ status: payload.status, evidenceFile, hardFailures: failed, cleanup: finalCleanup }, null, 2)}\n`); process.exitCode = payload.status === "PASS_W02_INTERNAL_SECURITY_RUNTIME" ? 0 : 2;
  } catch { await Promise.all([control?.$disconnect().catch(() => undefined), directA?.$disconnect().catch(() => undefined), directB?.$disconnect().catch(() => undefined), directNone?.$disconnect().catch(() => undefined)]); const finalCleanup = cleanup(); write({ status: finalCleanup.ok ? "FAIL_SETUP_OR_HARNESS" : "FAIL_CLEANUP", startedAt, finishedAt: new Date().toISOString(), environment: "disposable-postgresql-audit", databaseAlias: database, phase, mandatoryIds, cleanup: finalCleanup, credentialsPersisted: false, productionResourcesTouched: false, rawGucIdentityUsed: false }); process.exitCode = 2; }
}
void main();
