import { chmodSync, cpSync, mkdtempSync, readFileSync, rmSync, statSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { randomBytes, createHash } from "node:crypto";
import { spawnSync } from "node:child_process";
import { PrismaClient } from "@prisma/client";

const suffix = `${Date.now()}_${process.pid}`; const evidenceFile = `/tmp/w02-financial-migration-rehearsal-${suffix}.json`; const dbs = [`asas_mgr_clean_${suffix}`, `asas_mgr_upgrade_${suffix}`, `asas_mgr_recovery_${suffix}`]; const roles = [`mgr_migrator_${suffix}`, `mgr_a_${suffix}`, `mgr_b_${suffix}`, `mgr_none_${suffix}`]; const [migrator, a, b, none] = roles; const secrets = Object.fromEntries(roles.map((role) => [role, randomBytes(30).toString("base64url")])); const orgA = "11111111-1111-4111-8111-111111111111"; const orgB = "22222222-2222-4222-8222-222222222222"; const ids = ["MGR-F01", "MGR-F02", "MGR-F03", "MGR-F04", "MGR-F05", "MGR-F06", "MGR-F07", "MGR-F08", "MGR-F09", "MGR-F10"]; const evidence: Array<Record<string, unknown>> = [];
const admin = (sql: string, db = "postgres") => { const r = spawnSync("sudo", ["-u", "postgres", "psql", "-d", db, "-X", "-v", "ON_ERROR_STOP=1", "-At"], { input: sql, encoding: "utf8" }); if (r.status !== 0) throw new Error("AUDIT_ADMIN_SQL_FAILED"); return r.stdout.trim(); };
const url = (db: string, role: string) => `postgresql://${role}:${secrets[role]}@127.0.0.1:5432/${db}?schema=public`;
const deploy = (db: string, schema = "prisma/schema.prisma") => spawnSync("./node_modules/.bin/prisma", ["migrate", "deploy", "--schema", schema], { cwd: process.cwd(), env: { ...process.env, DATABASE_URL: url(db, migrator) }, encoding: "utf8" }).status === 0;
const safe = (fn: () => boolean) => { try { return fn(); } catch { return false; } };
const record = (id: string, expected: string, actual: () => boolean) => evidence.push({ id, expected, result: safe(actual) ? "PASS" : "FAIL", environment: "disposable-postgresql-audit", cleanupStatus: "PENDING" });
const setup = (db: string) => { admin(`CREATE DATABASE ${db} OWNER ${migrator};`); };
const rolesSql = () => admin(`CREATE ROLE ${migrator} LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS PASSWORD '${secrets[migrator]}'; CREATE ROLE ${a} LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS PASSWORD '${secrets[a]}'; CREATE ROLE ${b} LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS PASSWORD '${secrets[b]}'; CREATE ROLE ${none} LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS PASSWORD '${secrets[none]}';`);
const tenantSetup = (db: string) => admin(`GRANT CONNECT ON DATABASE ${db} TO ${a},${b},${none}; GRANT USAGE ON SCHEMA public,security TO ${a},${b},${none}; GRANT EXECUTE ON FUNCTION security.current_session_organization_id() TO ${a},${b},${none}; GRANT SELECT,INSERT,UPDATE,DELETE ON "donors","donation_campaigns","projects","donations","donor_communications","recurring_donations","invoices","budgets","budget_items","expenses" TO ${a},${b},${none}; INSERT INTO "organizations" ("id","name","createdAt","updatedAt") VALUES ('${orgA}','A',now(),now()),('${orgB}','B',now(),now()); INSERT INTO security.role_to_organization (role_oid,organization_id) VALUES ('${a}'::regrole::oid,'${orgA}'),('${b}'::regrole::oid,'${orgB}'); INSERT INTO "donors" ("id","organizationId","name","createdAt","updatedAt") VALUES ('donor-a','${orgA}','A',now(),now()),('donor-b','${orgB}','B',now(),now()); INSERT INTO "budgets" ("id","organizationId","title","fiscalYear","totalAmount","status","createdAt","updatedAt") VALUES ('budget-a','${orgA}','A','2026',100,'ACTIVE',now(),now()),('budget-b','${orgB}','B','2026',100,'ACTIVE',now(),now()),('budget-null',NULL,'N','2026',1,'DRAFT',now(),now()); INSERT INTO "budget_items" ("id","organizationId","budgetId","category","allocated") VALUES ('item-a','${orgA}','budget-a','A',10),('item-b','${orgB}','budget-b','B',10);` , db);
const policyState = (db: string) => admin("SELECT count(*) FROM pg_class WHERE relname IN ('donors','donation_campaigns','projects','donations','donor_communications','recurring_donations','invoices','budgets','budget_items','expenses') AND relrowsecurity AND relforcerowsecurity", db);
async function query(db: string, role: string, sql: string) { const client = new PrismaClient({ datasources: { db: { url: url(db, role) } } }); try { return await client.$queryRawUnsafe<Array<Record<string, unknown>>>(sql); } finally { await client.$disconnect(); } }
async function fails(db: string, role: string, sql: string) { try { await query(db, role, sql); return false; } catch { return true; } }
function cleanup() { const errors: string[] = []; for (const db of dbs) { try { admin(`SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname='${db}' AND pid <> pg_backend_pid(); DROP DATABASE IF EXISTS ${db} WITH (FORCE);`); } catch { errors.push("DB_CLEANUP_FAILED"); } } for (const role of roles) try { admin(`DROP ROLE IF EXISTS ${role};`); } catch { errors.push("ROLE_CLEANUP_FAILED"); } const residue = admin(`SELECT datname FROM pg_database WHERE datname IN (${dbs.map((db) => `'${db}'`).join(",")}) UNION ALL SELECT rolname FROM pg_roles WHERE rolname IN (${roles.map((role) => `'${role}'`).join(",")});`); return { ok: errors.length === 0 && residue === "", errors, residueCount: residue ? residue.split("\n").filter(Boolean).length : 0 }; }
function write(payload: Record<string, unknown>) { writeFileSync(evidenceFile, `${JSON.stringify(payload, null, 2)}\n`, { mode: 0o600 }); chmodSync(evidenceFile, 0o600); }
async function main() { const startedAt = new Date().toISOString(); let work: string | undefined; try { rolesSql(); setup(dbs[0]); record("MGR-F01", "pristine official deploy applies both financial migrations", () => deploy(dbs[0]) && admin("SELECT count(*) FROM _prisma_migrations WHERE migration_name IN ('20260824090000_w02_rls_wave2_donor_donation','20260824093000_w02_rls_wave3_budget_expense') AND finished_at IS NOT NULL", dbs[0]) === "2" && policyState(dbs[0]) === "10");
    work = mkdtempSync(join(tmpdir(), "w02-pre-wave2-")); cpSync("prisma", join(work, "prisma"), { recursive: true }); rmSync(join(work, "prisma/migrations/20260824090000_w02_rls_wave2_donor_donation"), { recursive: true }); rmSync(join(work, "prisma/migrations/20260824093000_w02_rls_wave3_budget_expense"), { recursive: true }); setup(dbs[1]); const preSchema = join(work, "prisma/schema.prisma"); record("MGR-F02", "pre-Wave2 baseline deploy omits financial policy migrations", () => deploy(dbs[1], preSchema) && admin("SELECT count(*) FROM _prisma_migrations WHERE migration_name LIKE '2026082409%'", dbs[1]) === "0" && policyState(dbs[1]) === "0");
    tenantSetup(dbs[1]); cpSync("prisma/migrations/20260824090000_w02_rls_wave2_donor_donation", join(work, "prisma/migrations/20260824090000_w02_rls_wave2_donor_donation"), { recursive: true }); cpSync("prisma/migrations/20260824093000_w02_rls_wave3_budget_expense", join(work, "prisma/migrations/20260824093000_w02_rls_wave3_budget_expense"), { recursive: true }); record("MGR-F03", "upgrade uses only official forward migrations and enables ten FORCE RLS tables", () => deploy(dbs[1], preSchema) && admin("SELECT count(*) FROM _prisma_migrations WHERE migration_name IN ('20260824090000_w02_rls_wave2_donor_donation','20260824093000_w02_rls_wave3_budget_expense') AND finished_at IS NOT NULL", dbs[1]) === "2" && policyState(dbs[1]) === "10");
    record("MGR-F04", "A/B direct reads see only their own financial roots after upgrade", () => false); const aDonors = await query(dbs[1], a, 'SELECT id FROM "donors" ORDER BY id'); const bBudgets = await query(dbs[1], b, 'SELECT id FROM "budgets" ORDER BY id'); evidence[evidence.length - 1].result = aDonors.length === 1 && aDonors[0].id === "donor-a" && bBudgets.length === 1 && bBudgets[0].id === "budget-b" ? "PASS" : "FAIL";
    record("MGR-F05", "foreign parent children are rejected after upgrade", () => false); evidence[evidence.length - 1].result = await fails(dbs[1], a, `INSERT INTO "budget_items" ("id","organizationId","budgetId","category","allocated") VALUES ('foreign-item','${orgA}','budget-b','X',1)`) && await fails(dbs[1], a, `INSERT INTO "donations" ("id","organizationId","donorId","amount","paymentMethod","paymentRef","status","createdAt","updatedAt") VALUES ('foreign-donation','${orgA}','donor-b',1,'CARD','x','COMPLETED',now(),now())`) ? "PASS" : "FAIL";
    record("MGR-F06", "unmapped roles and nullable roots fail closed after upgrade", () => false); const noneBudgets = await query(dbs[1], none, 'SELECT id FROM "budgets"'); evidence[evidence.length - 1].result = noneBudgets.length === 0 && await fails(dbs[1], a, `INSERT INTO "budgets" ("id","organizationId","title","fiscalYear","totalAmount","status","createdAt","updatedAt") VALUES ('null-budget',NULL,'N','2026',1,'DRAFT',now(),now())`) ? "PASS" : "FAIL";
    record("MGR-F07", "migration history and source hashes preserve official forward-only files", () => createHash("sha256").update(readFileSync("prisma/migrations/20260824090000_w02_rls_wave2_donor_donation/migration.sql")).digest("hex") === createHash("sha256").update(readFileSync(join(work!, "prisma/migrations/20260824090000_w02_rls_wave2_donor_donation/migration.sql"))).digest("hex") && admin("SELECT count(*) FROM _prisma_migrations WHERE rolled_back_at IS NOT NULL", dbs[1]) === "0");
    setup(dbs[2]); record("MGR-F08", "forward-safe recovery is disposal then clean official deploy, not historical rollback", () => deploy(dbs[2]) && policyState(dbs[2]) === "10"); tenantSetup(dbs[2]); const recoveryA = await query(dbs[2], a, 'SELECT id FROM "budgets" ORDER BY id'); record("MGR-F09", "recovered clean database re-enforces mapped A tenant visibility", () => recoveryA.length === 1 && recoveryA[0].id === "budget-a"); record("MGR-F10", "evidence IDs are exact, sources forbid raw GUC identity, and no credentials persist", () => ids.slice(0, -1).every((id) => evidence.some((entry) => entry.id === id)) && new Set(evidence.map((entry) => entry.id)).size === evidence.length && !/current_setting|set_config/.test(readFileSync("prisma/migrations/20260824090000_w02_rls_wave2_donor_donation/migration.sql", "utf8") + readFileSync("prisma/migrations/20260824093000_w02_rls_wave3_budget_expense/migration.sql", "utf8")));
    rmSync(work, { recursive: true, force: true }); work = undefined; const clean = cleanup(); for (const entry of evidence) entry.cleanupStatus = clean.ok ? "PASS" : "FAIL"; const result = evidence.length === ids.length && evidence.every((entry) => entry.result === "PASS") && clean.ok ? "PASS_FINANCIAL_MIGRATION_REHEARSAL" : "FAIL"; write({ status: result, startedAt, finishedAt: new Date().toISOString(), environment: "disposable-postgresql-audit", mandatoryIds: ids, evidence, cleanup: clean, credentialsPersisted: false, productionResourcesTouched: false, rawGucIdentityUsed: false, rollbackClaim: "No production rollback: the disposable upgraded database was discarded and rebuilt by official forward migrations." }); process.stdout.write(`${JSON.stringify({ status: result, evidenceFile, cleanup: clean }, null, 2)}\n`); process.exitCode = result === "PASS_FINANCIAL_MIGRATION_REHEARSAL" ? 0 : 2;
  } catch { if (work) rmSync(work, { recursive: true, force: true }); const clean = cleanup(); write({ status: clean.ok ? "FAIL_SETUP_OR_HARNESS" : "FAIL_CLEANUP", startedAt, finishedAt: new Date().toISOString(), environment: "disposable-postgresql-audit", mandatoryIds: ids, evidence, cleanup: clean, credentialsPersisted: false, productionResourcesTouched: false, rawGucIdentityUsed: false }); process.exitCode = 2; } }
void main();
