import { randomBytes } from "node:crypto";
import { chmodSync, readFileSync, writeFileSync } from "node:fs";
import { spawnSync } from "node:child_process";
import { PrismaClient } from "@prisma/client";
import { BrokerDeniedError, TenantAccessBroker } from "../src/lib/tenant-access-broker";
import { TenantBoundPrismaCredentialAuthority, TenantBoundPrismaExecutor, type TenantConnectionProvider } from "../src/lib/tenant-bound-prisma-authority";
import { BeneficiaryRepository } from "../src/lib/beneficiary-repository";
import type { TenantContext } from "../src/lib/tenant-context";

const suffix = `${Date.now()}_${process.pid}`;
const database = `asas_rls_wave1_audit_${suffix}`;
const migrator = `rls_wave1_migrator_${suffix}`;
const controlRole = `rls_wave1_control_${suffix}`;
const tenantA1 = `rls_wave1_a1_${suffix}`;
const tenantA2 = `rls_wave1_a2_${suffix}`;
const tenantB1 = `rls_wave1_b1_${suffix}`;
const tenantNoMap = `rls_wave1_none_${suffix}`;
const evidenceFile = `/tmp/w02-rls-wave1-beneficiary-evidence-${suffix}.json`;
const randomPassword = () => randomBytes(30).toString("base64url");
const passwords = { migrator: randomPassword(), control: randomPassword(), a1: randomPassword(), a2: randomPassword(), b1: randomPassword(), none: randomPassword() };
const orgA = "11111111-1111-4111-8111-111111111111";
const orgB = "22222222-2222-4222-8222-222222222222";
const userA = "aaaaaaaa-0000-4000-8000-000000000001";
const userB = "bbbbbbbb-0000-4000-8000-000000000002";
const membershipA = "aaaaaaaa-0000-4000-8000-000000000101";
const membershipB = "bbbbbbbb-0000-4000-8000-000000000102";
const mandatoryIds = ["R01", "R02", "R03", "R04", "R05", "R06", "R07", "R08", "R09", "R10", "R11", "R12", "R13", "R14", "R15"];
const evidence: Array<Record<string, unknown>> = [];

function run(command: string, args: string[], options: Record<string, unknown> = {}) { return spawnSync(command, args, { encoding: "utf8", ...options }); }
function adminSql(sql: string, db = "postgres") { const out = run("sudo", ["-u", "postgres", "psql", "-d", db, "-X", "-v", "ON_ERROR_STOP=1", "-At"], { input: sql }); if (out.status !== 0) throw new Error("AUDIT_ADMIN_SQL_FAILED"); return out.stdout.trim(); }
function writeEvidence(payload: Record<string, unknown>) { writeFileSync(evidenceFile, `${JSON.stringify(payload, null, 2)}\n`, { mode: 0o600 }); chmodSync(evidenceFile, 0o600); }
function context(input: { organizationId: string; userId: string; membershipId: string; correlationId: string }): TenantContext { return Object.freeze({ ...input, sessionVersion: 1, policySnapshotVersion: 1 }); }
async function record(id: string, expected: string, action: () => Promise<unknown>, check: (actual: unknown) => boolean) { try { const actual = await action(); evidence.push({ id, expected, actual: typeof actual === "string" || typeof actual === "boolean" || typeof actual === "number" ? actual : "REDACTED_OBJECT", result: check(actual) ? "PASS" : "FAIL", timestamp: new Date().toISOString(), environment: "disposable-postgresql-audit", cleanupStatus: "PENDING" }); } catch { evidence.push({ id, expected, actual: "REDACTED_EXCEPTION", result: "FAIL", timestamp: new Date().toISOString(), environment: "disposable-postgresql-audit", cleanupStatus: "PENDING" }); } }
async function denied(action: () => Promise<unknown>, code?: string) { try { await action(); return false; } catch (error) { return code ? error instanceof BrokerDeniedError && error.code === code : true; } }
function cleanup() { const roles = [tenantA1, tenantA2, tenantB1, tenantNoMap, controlRole, migrator]; const errors: string[] = []; try { adminSql(`SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname='${database}' AND pid <> pg_backend_pid();`); } catch { errors.push("TERMINATE_FAILED"); } try { adminSql(`DROP DATABASE IF EXISTS ${database};`); } catch { errors.push("DROP_DATABASE_FAILED"); } for (const role of roles) try { adminSql(`DROP ROLE IF EXISTS ${role};`); } catch { errors.push("DROP_ROLE_FAILED"); } let residue = ""; try { residue = adminSql(`SELECT datname FROM pg_database WHERE datname='${database}' UNION ALL SELECT rolname FROM pg_roles WHERE rolname IN (${roles.map((role) => `'${role}'`).join(",")});`); } catch { errors.push("RESIDUE_SCAN_FAILED"); } return { ok: errors.length === 0 && residue === "", errors, residueCount: residue ? residue.split("\n").filter(Boolean).length : 0 }; }

async function main() {
  let controlPrisma: PrismaClient | null = null;
  let directA: PrismaClient | null = null;
  let directB: PrismaClient | null = null;
  let directNoMap: PrismaClient | null = null;
  const startedAt = new Date().toISOString();
  try {
    adminSql(`CREATE ROLE ${migrator} LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS PASSWORD '${passwords.migrator}'; CREATE DATABASE ${database} OWNER ${migrator}; CREATE ROLE ${controlRole} LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS PASSWORD '${passwords.control}'; CREATE ROLE ${tenantA1} LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS PASSWORD '${passwords.a1}'; CREATE ROLE ${tenantA2} LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS PASSWORD '${passwords.a2}'; CREATE ROLE ${tenantB1} LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS PASSWORD '${passwords.b1}'; CREATE ROLE ${tenantNoMap} LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS PASSWORD '${passwords.none}';`);
    const migrationUrl = `postgresql://${migrator}:${passwords.migrator}@127.0.0.1:5432/${database}?schema=public`;
    if (run("./node_modules/.bin/prisma", ["migrate", "deploy", "--schema", "prisma/schema.prisma"], { env: { ...process.env, DATABASE_URL: migrationUrl } }).status !== 0) throw new Error("MIGRATION_DEPLOY_FAILED");
    adminSql(`GRANT CONNECT ON DATABASE ${database} TO ${controlRole}, ${tenantA1}, ${tenantA2}, ${tenantB1}, ${tenantNoMap}; GRANT USAGE ON SCHEMA public, security TO ${controlRole}, ${tenantA1}, ${tenantA2}, ${tenantB1}, ${tenantNoMap}; GRANT EXECUTE ON FUNCTION security.current_session_organization_id() TO ${controlRole}, ${tenantA1}, ${tenantA2}, ${tenantB1}, ${tenantNoMap}; GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "organizations", "users", "organization_memberships", "tenant_database_principals", "tenant_access_leases", "tenant_broker_audit_events" TO ${controlRole}; GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "beneficiaries", "beneficiary_documents", "audit_logs" TO ${tenantA1}, ${tenantA2}, ${tenantB1}, ${tenantNoMap};`, database);
    adminSql(`INSERT INTO "organizations" ("id","name","createdAt","updatedAt") VALUES ('${orgA}','Organization A',now(),now()),('${orgB}','Organization B',now(),now()); INSERT INTO "users" ("id","name","email","role","isActive","authVersion","activeOrganizationId","createdAt","updatedAt") VALUES ('${userA}','User A','a-${suffix}@audit.invalid','MEMBER',true,1,'${orgA}',now(),now()),('${userB}','User B','b-${suffix}@audit.invalid','MEMBER',true,1,'${orgB}',now(),now()); INSERT INTO "organization_memberships" ("id","organizationId","userId","role","isActive","policyVersion","createdAt","updatedAt") VALUES ('${membershipA}','${orgA}','${userA}','MEMBER',true,1,now(),now()),('${membershipB}','${orgB}','${userB}','MEMBER',true,1,now(),now()); INSERT INTO security.role_to_organization (role_oid, organization_id) VALUES ('${tenantA1}'::regrole::oid,'${orgA}'),('${tenantB1}'::regrole::oid,'${orgB}'); INSERT INTO "tenant_database_principals" ("id","organizationId","principalName","credentialReference","generation","status","activatedAt","createdAt","updatedAt") VALUES ('principal-a1','${orgA}','${tenantA1}','audit://rls/a1',1,'ACTIVE',now(),now(),now()),('principal-b1','${orgB}','${tenantB1}','audit://rls/b1',1,'ACTIVE',now(),now(),now()); INSERT INTO "beneficiaries" ("id","organizationId","name","phone","status","createdAt","updatedAt") VALUES ('beneficiary-a','${orgA}','Beneficiary A','0500000001','ACTIVE',now(),now()),('beneficiary-b','${orgB}','Beneficiary B','0500000002','ACTIVE',now(),now()); INSERT INTO "beneficiary_documents" ("id","beneficiaryId","name","fileType","fileUrl","uploadedAt") VALUES ('document-a','beneficiary-a','A Doc','application/pdf','private://a',now()),('document-b','beneficiary-b','B Doc','application/pdf','private://b',now()); INSERT INTO "beneficiaries" ("id","organizationId","name","phone","status","createdAt","updatedAt") VALUES ('beneficiary-unmapped',NULL,'Unmapped','0500000000','ACTIVE',now(),now());`, database);
    const url = (role: string, password: string) => `postgresql://${role}:${password}@127.0.0.1:5432/${database}?schema=public`;
    controlPrisma = new PrismaClient({ datasources: { db: { url: url(controlRole, passwords.control) } } });
    directA = new PrismaClient({ datasources: { db: { url: url(tenantA1, passwords.a1) } } });
    directB = new PrismaClient({ datasources: { db: { url: url(tenantB1, passwords.b1) } } });
    directNoMap = new PrismaClient({ datasources: { db: { url: url(tenantNoMap, passwords.none) } } });
    const entries = new Map<string, { principalName: string; url: string }>([["audit://rls/a1", { principalName: tenantA1, url: url(tenantA1, passwords.a1) }], ["audit://rls/a2", { principalName: tenantA2, url: url(tenantA2, passwords.a2) }], ["audit://rls/b1", { principalName: tenantB1, url: url(tenantB1, passwords.b1) }]]);
    const unavailable = new Set<string>(); let checkoutCount = 0; let discardCount = 0;
    const provider: TenantConnectionProvider = { async checkout(input) { const entry = entries.get(input.credentialReference); if (!entry || unavailable.has(input.credentialReference) || entry.principalName !== input.principalName) throw new Error("AUTHORITY_UNAVAILABLE"); const prisma = new PrismaClient({ datasources: { db: { url: entry.url } } }); const identity = await prisma.$queryRawUnsafe<Array<{ session_user: string }>>("SELECT session_user"); if (identity[0]?.session_user !== input.principalName) { await prisma.$disconnect(); throw new Error("SESSION_USER_MISMATCH"); } checkoutCount += 1; return { prisma, discard: async () => { discardCount += 1; await prisma.$disconnect(); } }; } };
    const authority = new TenantBoundPrismaCredentialAuthority(provider);
    const broker = new TenantAccessBroker(controlPrisma, authority, 5_000);
    const executor = new TenantBoundPrismaExecutor(broker);
    const ctxA = context({ organizationId: orgA, userId: userA, membershipId: membershipA, correlationId: "rls-wave1-a" });
    const ctxB = context({ organizationId: orgB, userId: userB, membershipId: membershipB, correlationId: "rls-wave1-b" });
    const sessionUser = (db: PrismaClient) => db.$queryRawUnsafe<Array<{ session_user: string }>>("SELECT session_user").then((rows) => rows[0]?.session_user);

    await record("R01", "unmapped login principal sees zero rows and cannot write", async () => { const visible = await directNoMap!.beneficiary.count(); const writeDenied = await denied(() => directNoMap!.beneficiary.create({ data: { organizationId: orgA, name: "Denied", phone: "0500000011", status: "ACTIVE" } })); return visible === 0 && writeDenied; }, (actual) => actual === true);
    await record("R02", "tenant A direct read/update/insert against B are denied by RLS", async () => { const read = await directA!.beneficiary.findUnique({ where: { id: "beneficiary-b" } }); const update = await directA!.beneficiary.updateMany({ where: { id: "beneficiary-b" }, data: { name: "forbidden" } }); const writeDenied = await denied(() => directA!.beneficiary.create({ data: { organizationId: orgB, name: "Denied", phone: "0500000012", status: "ACTIVE" } })); return read === null && update.count === 0 && writeDenied; }, (actual) => actual === true);
    await record("R03", "tenant B direct read/update/insert against A are denied by RLS", async () => { const read = await directB!.beneficiary.findUnique({ where: { id: "beneficiary-a" } }); const update = await directB!.beneficiary.updateMany({ where: { id: "beneficiary-a" }, data: { name: "forbidden" } }); const writeDenied = await denied(() => directB!.beneficiary.create({ data: { organizationId: orgA, name: "Denied", phone: "0500000013", status: "ACTIVE" } })); return read === null && update.count === 0 && writeDenied; }, (actual) => actual === true);
    await record("R04", "raw GUC and client organization spoof do not change session_user RLS identity", async () => { const before = await sessionUser(directA!); await directA!.$executeRawUnsafe(`SET LOCAL app.organization_id = '${orgB}'`); const after = await sessionUser(directA!); const foreign = await directA!.beneficiary.findUnique({ where: { id: "beneficiary-b" } }); return before === tenantA1 && after === tenantA1 && foreign === null; }, (actual) => actual === true);
    await record("R05", "SET ROLE cannot switch a tenant login into another role", async () => { const deniedSetRole = await denied(() => directA!.$executeRawUnsafe(`SET ROLE ${tenantB1}`)); const identity = await sessionUser(directA!); return deniedSetRole && identity === tenantA1; }, (actual) => actual === true);
    await record("R06", "authority discards each tenant client rather than reusing a cross-tenant pool", async () => { await executor.execute(ctxA, sessionUser); await executor.execute(ctxB, sessionUser); return checkoutCount >= 2 && discardCount >= checkoutCount; }, (actual) => actual === true);
    await record("R07", "parallel A/B runtime operations retain own session_user and rows", async () => { const [a, b] = await Promise.all([executor.execute(ctxA, async (db) => ({ identity: await sessionUser(db), rows: await db.beneficiary.count() })), executor.execute(ctxB, async (db) => ({ identity: await sessionUser(db), rows: await db.beneficiary.count() }))]); return a.identity === tenantA1 && b.identity === tenantB1 && a.rows === 1 && b.rows === 1; }, (actual) => actual === true);
    await record("R08", "revoked lease and stale session are denied before RLS data-plane execution", async () => { const lease = await broker.issueLease(ctxB); await broker.revokeLease(lease.leaseId, ctxB.correlationId); const revoked = await denied(() => broker.execute(ctxB, lease, async () => "unexpected"), "LEASE_REVOKED"); await controlPrisma!.user.update({ where: { id: userB }, data: { authVersion: 2 } }); const stale = await denied(() => executor.execute(ctxB, sessionUser), "STALE_SESSION"); return revoked && stale; }, (actual) => actual === true);
    await record("R09", "provider failure denies runtime without a global Prisma fallback", async () => { unavailable.add("audit://rls/a1"); const failed = await denied(() => executor.execute(ctxA, sessionUser), "AUTHORITY_OR_OPERATION_FAILURE"); unavailable.delete("audit://rls/a1"); return failed; }, (actual) => actual === true);
    await record("R10", "role-map rotation rejects old A login and authorizes only new mapped principal", async () => { await controlPrisma!.tenantDatabasePrincipal.update({ where: { id: "principal-a1" }, data: { status: "REVOKED", revokedAt: new Date() } }); adminSql(`UPDATE security.role_to_organization SET revoked_at = now() WHERE role_oid = '${tenantA1}'::regrole::oid AND revoked_at IS NULL; INSERT INTO security.role_to_organization (role_oid, organization_id) VALUES ('${tenantA2}'::regrole::oid, '${orgA}');`, database); await controlPrisma!.tenantDatabasePrincipal.create({ data: { id: "principal-a2", organizationId: orgA, principalName: tenantA2, credentialReference: "audit://rls/a2", generation: 2, status: "ACTIVE", activatedAt: new Date() } }); const oldRows = await directA!.beneficiary.count(); const newIdentity = await executor.execute(ctxA, sessionUser); return oldRows === 0 && newIdentity === tenantA2; }, (actual) => actual === true);
    await record("R11", "BeneficiaryDocument child and parent join remain tenant-isolated", async () => { const own = await executor.execute(ctxA, (db) => db.beneficiary.findUnique({ where: { id: "beneficiary-a" }, include: { documents: true } })); const foreign = await executor.execute(ctxA, (db) => db.beneficiary.findUnique({ where: { id: "beneficiary-b" }, include: { documents: true } })); const directChildren = await executor.execute(ctxA, (db) => db.beneficiaryDocument.count()); return own?.documents.length === 1 && foreign === null && directChildren === 1; }, (actual) => actual === true);
    await record("R12", "BeneficiaryRepository runs through Broker-bound tenant Prisma under FORCE RLS", async () => { const repository = new BeneficiaryRepository(executor); const result = await repository.list(ctxA, { skip: 0, take: 20 }); return result.data.length === 1 && result.data[0]?.organizationId === orgA; }, (actual) => actual === true);
    await record("R13", "Beneficiary dashboard routes retain server context, permission guard and repository usage", async () => { const listPage = readFileSync("src/app/(dashboard)/beneficiaries/page.tsx", "utf8"); const detailPage = readFileSync("src/app/(dashboard)/beneficiaries/[id]/page.tsx", "utf8"); const repository = readFileSync("src/lib/beneficiary-repository.ts", "utf8"); return /requireTenantContext/.test(listPage) && /requireTenantContext/.test(detailPage) && /requirePermission/.test(listPage) && /requirePermission/.test(detailPage) && !/from \"@\/lib\/db\"/.test(repository); }, (actual) => actual === true);
    await record("R14", "tenant principals cannot read or create nullable/unmapped beneficiary roots", async () => { const unmapped = await directA!.beneficiary.findUnique({ where: { id: "beneficiary-unmapped" } }); const nullWriteDenied = await denied(() => directA!.beneficiary.create({ data: { organizationId: null, name: "Null", phone: "0500000014", status: "ACTIVE" } })); return unmapped === null && nullWriteDenied; }, (actual) => actual === true);
    await record("R15", "clean migration rehearsal enables and forces RLS with all three policies and non-bypass tenant roles", async () => { const migration = adminSql("SELECT count(*) FROM _prisma_migrations WHERE migration_name = '20260823080000_w02_rls_wave1_beneficiary_session_user' AND finished_at IS NOT NULL", database); const tables = adminSql("SELECT count(*) FROM pg_class WHERE relname IN ('beneficiaries','beneficiary_documents','audit_logs') AND relrowsecurity AND relforcerowsecurity", database); const policies = adminSql("SELECT count(*) FROM pg_policies WHERE schemaname='public' AND policyname IN ('beneficiary_session_user_tenant_isolation','beneficiary_document_session_user_tenant_isolation','beneficiary_audit_log_session_user_tenant_isolation')", database); const unsafe = adminSql(`SELECT count(*) FROM pg_roles WHERE rolname IN ('${tenantA1}','${tenantA2}','${tenantB1}','${tenantNoMap}') AND (rolsuper OR rolbypassrls)`, database); return migration === "1" && tables === "3" && policies === "3" && unsafe === "0"; }, (actual) => actual === true);

    const hardFailures = evidence.filter((item) => item.result !== "PASS").map((item) => item.id);
    const payload: Record<string, unknown> = { status: hardFailures.length === 0 ? "PASS_RLS_WAVE1_BENEFICIARY_RUNTIME" : "FAIL", startedAt, finishedAt: new Date().toISOString(), databaseAlias: database, environment: "disposable-postgresql-audit", mandatoryIds, evidence, hardFailures, cleanup: { ok: false, residueCount: -1 }, credentialsPersisted: false, productionResourcesTouched: false, rawGucIdentityUsed: false, globalPrismaFallback: false, ownerOrBypassUsedForTenantEvidence: false };
    await Promise.all([controlPrisma.$disconnect(), directA.$disconnect(), directB.$disconnect(), directNoMap.$disconnect()]); controlPrisma = null; directA = null; directB = null; directNoMap = null; const finalCleanup = cleanup(); payload.cleanup = finalCleanup; if (!finalCleanup.ok) payload.status = "FAIL_CLEANUP"; for (const item of evidence) item.cleanupStatus = finalCleanup.ok ? "PASS" : "FAIL"; writeEvidence(payload); process.stdout.write(`${JSON.stringify({ status: payload.status, evidenceFile, hardFailures, cleanup: finalCleanup }, null, 2)}\n`); process.exitCode = payload.status === "PASS_RLS_WAVE1_BENEFICIARY_RUNTIME" ? 0 : 2;
  } catch { await Promise.all([controlPrisma?.$disconnect().catch(() => undefined), directA?.$disconnect().catch(() => undefined), directB?.$disconnect().catch(() => undefined), directNoMap?.$disconnect().catch(() => undefined)]); const finalCleanup = cleanup(); writeEvidence({ status: finalCleanup.ok ? "FAIL_SETUP_OR_HARNESS" : "FAIL_CLEANUP", startedAt, finishedAt: new Date().toISOString(), databaseAlias: database, error: "REDACTED_HARNESS_ERROR", mandatoryIds, cleanup: finalCleanup, credentialsPersisted: false, productionResourcesTouched: false }); process.stderr.write(`RLS Wave 1 proof failed; redacted evidence: ${evidenceFile}\n`); process.exitCode = 2; }
}
void main();
