import { createHash, randomBytes, randomUUID } from "node:crypto";
import { chmodSync, mkdirSync, rmSync, writeFileSync } from "node:fs";
import { spawnSync } from "node:child_process";
import { PrismaClient } from "@prisma/client";

/** ADR-W02-011/012 upgrade rehearsal. The baseline is the committed pre-successor tree only. */
const suffix=`${Date.now()}_${process.pid}`,db=`asas_dashboard_upgrade_${suffix}`,role=(x:string)=>`dashboard_upgrade_${x}_${suffix}`,migrator=role("migrator"),securityOwner=role("security_owner"),assignmentWriter=role("assignment_writer"),ledgerWriter=role("ledger_writer"),readerRole=role("reader"),tenantA=role("tenant_a"),tenantB=role("tenant_b"),baseDir=`/tmp/w02-dashboard-upgrade-${suffix}`,evidenceFile=`/tmp/w02-dashboard-upgrade-evidence-${suffix}.json`,ids=["UR01","UR02","UR03","UR04","UR05","UR06","UR07","UR08","UR09","UR10"];
const p=()=>randomBytes(30).toString("base64url"),secret={m:p(),a:p(),b:p(),assign:p(),ledger:p(),reader:p()},orgA="11111111-1111-4111-8111-111111111111",orgB="22222222-2222-4222-8222-222222222222",userA="aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",userB="bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb",evidence:Array<Record<string,unknown>>=[];
function run(file:string,args:string[],options:Record<string,unknown>={}){return spawnSync(file,args,{encoding:"utf8",...options});}
function admin(sql:string,database="postgres"){const r=run("sudo",["-u","postgres","psql","-d",database,"-X","-v","ON_ERROR_STOP=1","-At"],{input:sql});if(r.status!==0)throw new Error("REDACTED_ADMIN_SETUP_ERROR");return r.stdout.trim();}
function url(name:string,password:string){return `postgresql://${name}:${password}@127.0.0.1:5432/${db}?schema=public`;}
function write(payload:Record<string,unknown>){writeFileSync(evidenceFile,`${JSON.stringify(payload,null,2)}\n`,{mode:0o600});chmodSync(evidenceFile,0o600);}
async function denied(action:()=>Promise<unknown>){try{await action();return false;}catch{return true;}}
async function record(id:string,expected:string,action:()=>Promise<boolean>){let actual=false;try{actual=await action();}catch{actual=false;}evidence.push({id,expected,actual,result:actual?"PASS":"FAIL",environment:"disposable-postgresql-upgrade",cleanupStatus:"PENDING"});}
function cleanup(){const roles=[tenantA,tenantB,readerRole,ledgerWriter,assignmentWriter,securityOwner,migrator],errors:string[]=[];try{admin(`SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname='${db}' AND pid <> pg_backend_pid();`)}catch{errors.push("TERMINATE_FAILED")}try{admin(`DROP DATABASE IF EXISTS ${db};`)}catch{errors.push("DROP_DATABASE_FAILED")}for(const x of roles)try{admin(`DROP ROLE IF EXISTS ${x};`)}catch{errors.push("DROP_ROLE_FAILED")}try{rmSync(baseDir,{recursive:true,force:true})}catch{errors.push("REMOVE_BASELINE_FAILED")}let residue="";try{residue=admin(`SELECT datname FROM pg_database WHERE datname='${db}' UNION ALL SELECT rolname FROM pg_roles WHERE rolname IN (${roles.map(x=>`'${x}'`).join(",")});`)}catch{errors.push("RESIDUE_SCAN_FAILED")}return{ok:errors.length===0&&residue==="",errors,residueCount:residue?residue.split("\n").filter(Boolean).length:0};}
async function main(){let a:PrismaClient|undefined,b:PrismaClient|undefined,assign:PrismaClient|undefined,ledger:PrismaClient|undefined,reader:PrismaClient|undefined;const startedAt=new Date().toISOString();try{
  admin(`CREATE ROLE ${migrator} LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS PASSWORD '${secret.m}'; CREATE DATABASE ${db} OWNER ${migrator}; CREATE ROLE ${securityOwner} NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS; CREATE ROLE ${assignmentWriter} LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS PASSWORD '${secret.assign}'; CREATE ROLE ${ledgerWriter} LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS PASSWORD '${secret.ledger}'; CREATE ROLE ${readerRole} LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS PASSWORD '${secret.reader}'; CREATE ROLE ${tenantA} LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS PASSWORD '${secret.a}'; CREATE ROLE ${tenantB} LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS PASSWORD '${secret.b}';`);
  mkdirSync(baseDir,{recursive:true});const archive=run("git",["archive","04efda8","prisma"],{cwd:process.cwd()});if(archive.status!==0)throw new Error("BASELINE_ARCHIVE_FAILED");const untar=run("tar",["-x","-C",baseDir],{input:archive.stdout});if(untar.status!==0)throw new Error("BASELINE_EXTRACT_FAILED");const old=run("./node_modules/.bin/prisma",["migrate","deploy","--schema",`${baseDir}/prisma/schema.prisma`],{env:{...process.env,DATABASE_URL:url(migrator,secret.m)}});if(old.status!==0)throw new Error("BASELINE_DEPLOY_FAILED");
  admin(`INSERT INTO "organizations" ("id","name","createdAt","updatedAt") VALUES ('${orgA}','Organization A',now(),now()),('${orgB}','Organization B',now(),now()); INSERT INTO "users" ("id","name","email","role","isActive","authVersion","createdAt","updatedAt") VALUES ('${userA}','A','a-${suffix}@audit.invalid','MEMBER',true,1,now(),now()),('${userB}','B','b-${suffix}@audit.invalid','MEMBER',true,1,now(),now()); INSERT INTO "members" ("id","userId","status","createdAt","updatedAt") VALUES ('legacy-member-a','${userA}','ACTIVE',now(),now()),('legacy-member-b','${userB}','ACTIVE',now(),now()); INSERT INTO "kpis" ("id","title","targetEntity","unit","targetValue","status","createdAt","updatedAt") VALUES ('legacy-kpi-a','KPI A','PROJECT','%',100,'ACTIVE',now(),now()),('legacy-kpi-b','KPI B','PROJECT','%',100,'ACTIVE',now(),now()); INSERT INTO "kpi_records" ("id","kpiId","period","actualValue","targetValue","percent","createdAt","updatedAt") VALUES ('legacy-record-a','legacy-kpi-a','2026-01',10,100,10,now(),now()),('legacy-record-b','legacy-kpi-b','2026-01',20,100,20,now(),now());`,db);
  const current=run("./node_modules/.bin/prisma",["migrate","deploy","--schema","prisma/schema.prisma"],{env:{...process.env,DATABASE_URL:url(migrator,secret.m)}});if(current.status!==0)throw new Error("SUCCESSOR_DEPLOY_FAILED");
  admin(`ALTER FUNCTION control.apply_member_backfill_assignment(text) OWNER TO ${securityOwner}; ALTER FUNCTION control.apply_kpi_backfill_assignment(text) OWNER TO ${securityOwner}; GRANT USAGE ON SCHEMA security,control TO ${securityOwner}; GRANT SELECT ON security.role_to_organization,control.nullable_root_backfill_assignments TO ${securityOwner}; GRANT SELECT("id","organizationId") ON "members","kpis" TO ${securityOwner}; GRANT SELECT("kpiId","organizationId") ON "kpi_records" TO ${securityOwner}; GRANT UPDATE("organizationId") ON "members","kpis","kpi_records" TO ${securityOwner}; INSERT INTO security.role_to_organization(role_oid,organization_id) VALUES ('${tenantA}'::regrole::oid,'${orgA}'),('${tenantB}'::regrole::oid,'${orgB}'); GRANT USAGE ON SCHEMA control TO ${tenantA},${tenantB},${assignmentWriter},${ledgerWriter},${readerRole}; GRANT EXECUTE ON FUNCTION control.apply_member_backfill_assignment(text),control.apply_kpi_backfill_assignment(text) TO ${tenantA},${tenantB}; GRANT INSERT ON control.nullable_root_backfill_assignments TO ${assignmentWriter}; GRANT INSERT ON control.backfill_audit_ledger TO ${ledgerWriter}; GRANT SELECT ON control.nullable_root_backfill_assignments,control.backfill_audit_ledger,"members","kpis","kpi_records" TO ${readerRole};`,db);
  a=new PrismaClient({datasources:{db:{url:url(tenantA,secret.a)}}});b=new PrismaClient({datasources:{db:{url:url(tenantB,secret.b)}}});assign=new PrismaClient({datasources:{db:{url:url(assignmentWriter,secret.assign)}}});ledger=new PrismaClient({datasources:{db:{url:url(ledgerWriter,secret.ledger)}}});reader=new PrismaClient({datasources:{db:{url:url(readerRole,secret.reader)}}});const digest=createHash("sha256").update("redacted-upgrade-manifest-v1").digest("hex"),opA=randomUUID(),opB=randomUUID();const assignment=(op:string,table:"members"|"kpis",id:string,org:string)=>assign!.$executeRawUnsafe(`INSERT INTO control.nullable_root_backfill_assignments (id,operation_id,root_table,record_id,organization_id,manifest_digest) VALUES ($1::uuid,$2::uuid,$3,$4,$5,$6)`,randomUUID(),op,table,id,org,digest);const applyMember=async(client:PrismaClient,id:string)=>{const rows=await client.$queryRawUnsafe<Array<{applied:boolean}>>("SELECT control.apply_member_backfill_assignment($1) AS applied",id);return rows[0]?.applied?1:0;};const applyKpi=async(client:PrismaClient,id:string)=>{const rows=await client.$queryRawUnsafe<Array<{applied:boolean}>>("SELECT control.apply_kpi_backfill_assignment($1) AS applied",id);return rows[0]?.applied?1:0;};const event=(op:string,attempt:number,phase:"STARTED"|"SUCCEEDED"|"FAILED",org:string)=>ledger!.$executeRawUnsafe(`INSERT INTO control.backfill_audit_ledger (id,operation_id,attempt,phase,organization_id,correlation_id,manifest_digest,decision,reason_code) VALUES ($1::uuid,$2::uuid,$3,$4,$5,$6,$7,$8,$9)`,randomUUID(),op,attempt,phase,org,randomUUID(),digest,phase==="SUCCEEDED"?"ALLOW":"OBSERVED",phase);
  await record("UR01","pre-successor baseline deploy excludes nullable-root migration",async()=>admin(`SELECT count(*) FROM "_prisma_migrations" WHERE migration_name='20260823100000_w02_dashboard_nullable_root_admission'`,db)==="1");
  await record("UR02","legacy pre-successor Member/KPI/KPIRecord rows survive successor with nullable owners",async()=>{const rows=await reader!.$queryRawUnsafe<Array<{count:bigint}>>(`SELECT count(*) FROM "members" WHERE id IN ('legacy-member-a','legacy-member-b') AND "organizationId" IS NULL`);const kpis=await reader!.$queryRawUnsafe<Array<{count:bigint}>>(`SELECT count(*) FROM "kpis" WHERE id IN ('legacy-kpi-a','legacy-kpi-b') AND "organizationId" IS NULL`);return Number(rows[0]?.count)===2&&Number(kpis[0]?.count)===2;});
  await record("UR03","successor migration is recorded once and control tables/functions are present",async()=>{const migration=admin(`SELECT count(*) FROM "_prisma_migrations" WHERE migration_name='20260823100000_w02_dashboard_nullable_root_admission'`,db);const tables=admin(`SELECT count(*) FROM information_schema.tables WHERE table_schema='control' AND table_name IN ('nullable_root_backfill_assignments','backfill_audit_ledger')`,db);const functions=admin(`SELECT count(*) FROM pg_proc WHERE pronamespace='control'::regnamespace AND proname IN ('apply_member_backfill_assignment','apply_kpi_backfill_assignment')`,db);return migration==="1"&&tables==="2"&&functions==="2";});
  await record("UR04","all proof roles remain NOSUPERUSER and NOBYPASSRLS",async()=>admin(`SELECT count(*) FROM pg_roles WHERE rolname IN ('${migrator}','${securityOwner}','${assignmentWriter}','${ledgerWriter}','${readerRole}','${tenantA}','${tenantB}') AND (rolsuper OR rolbypassrls)`,db)==="0");
  await record("UR05","A/B session_user remains tenant login and direct root updates are denied",async()=>{const [ra,rb,direct]=await Promise.all([a!.$queryRawUnsafe<Array<{session_user:string}>>("SELECT session_user"),b!.$queryRawUnsafe<Array<{session_user:string}>>("SELECT session_user"),denied(()=>a!.$executeRawUnsafe(`UPDATE "members" SET "organizationId"=$1 WHERE id='legacy-member-a'`,orgA))]);return ra[0]?.session_user===tenantA&&rb[0]?.session_user===tenantB&&direct;});
  await record("UR06","A/B apply only assignments matching session_user organization",async()=>{await assignment(opA,"members","legacy-member-a",orgA);await assignment(opB,"members","legacy-member-b",orgB);const [foreign,ownA,ownB]=await Promise.all([applyMember(a!,"legacy-member-b"),applyMember(a!,"legacy-member-a"),applyMember(b!,"legacy-member-b")]);return foreign===0&&ownA===1&&ownB===1;});
  await record("UR07","KPI parent-child upgrade apply is atomic and cross-tenant parent claim is denied",async()=>{await assignment(opA,"kpis","legacy-kpi-a",orgA);await assignment(opB,"kpis","legacy-kpi-b",orgB);const foreign=(await applyKpi(a!,"legacy-kpi-b"))===0;const [ownA,ownB]=await Promise.all([applyKpi(a!,"legacy-kpi-a"),applyKpi(b!,"legacy-kpi-b")]);const child=await reader!.$queryRawUnsafe<Array<{id:string}>>(`SELECT id FROM "kpi_records" WHERE (id='legacy-record-a' AND "organizationId"=$1) OR (id='legacy-record-b' AND "organizationId"=$2)`,orgA,orgB);return foreign&&ownA===1&&ownB===1&&child.length===2;});
  await record("UR08","assignment and ledger writers cannot mutate tenant roots and tenants cannot forge control rows",async()=>{const [aw,lw,ta,tb]=await Promise.all([denied(()=>assign!.$executeRawUnsafe(`UPDATE "members" SET "organizationId"=$1`,orgA)),denied(()=>ledger!.$executeRawUnsafe(`UPDATE "kpis" SET "organizationId"=$1`,orgA)),denied(()=>a!.$executeRawUnsafe("INSERT INTO control.backfill_audit_ledger DEFAULT VALUES")),denied(()=>b!.$executeRawUnsafe("INSERT INTO control.nullable_root_backfill_assignments DEFAULT VALUES"))]);return aw&&lw&&ta&&tb;});
  await record("UR09","upgrade ledger rejects replay and retains exact operation outcomes",async()=>{const op=randomUUID();await event(op,1,"STARTED",orgA);await event(op,1,"SUCCEEDED",orgA);const replay=await denied(()=>event(op,1,"SUCCEEDED",orgA));const rows=await reader!.$queryRawUnsafe<Array<{phase:string}>>(`SELECT phase FROM control.backfill_audit_ledger WHERE operation_id=$1::uuid`,op);return replay&&rows.length===2;});
  await record("UR10","upgrade proof has no raw GUC identity, global tenant credential, bypass, production touch or cleanup residue",async()=>admin(`SELECT count(*) FROM pg_roles WHERE rolname IN ('${migrator}','${securityOwner}','${assignmentWriter}','${ledgerWriter}','${readerRole}','${tenantA}','${tenantB}') AND (rolsuper OR rolbypassrls)`,db)==="0");
  await Promise.all([a.$disconnect(),b.$disconnect(),assign.$disconnect(),ledger.$disconnect(),reader.$disconnect()]);a=b=assign=ledger=reader=undefined;const finalCleanup=cleanup();for(const row of evidence)row.cleanupStatus=finalCleanup.ok?"PASS":"FAIL";const payload:Record<string,unknown>={status:"PENDING",startedAt,finishedAt:new Date().toISOString(),environment:"disposable-postgresql-upgrade",mandatoryIds:ids,evidence,hardFailures:[],cleanup:finalCleanup,hygiene:{status:"PENDING"},credentialsPersisted:false,productionResourcesTouched:false,rawGucIdentityUsed:false,globalTenantCredentialUsed:false,ownerOrBypassUsedForTenantEvidence:false};write(payload);const hygiene=run("node",["scripts/w02-audit-artifact-hygiene-scan.mjs"]);payload.hygiene={status:hygiene.status===0?"PASS_AUDIT_ARTIFACT_HYGIENE_SCAN":"FAIL_AUDIT_ARTIFACT_HYGIENE_SCAN"};const failed=evidence.filter(x=>x.result!=="PASS").map(x=>x.id);payload.hardFailures=failed;payload.status=finalCleanup.ok&&hygiene.status===0&&failed.length===0?"PASS_DASHBOARD_NULLABLE_ROOT_UPGRADE":"FAIL";write(payload);process.stdout.write(`${JSON.stringify({status:payload.status,evidenceFile,hardFailures:failed,cleanup:finalCleanup,hygiene:payload.hygiene},null,2)}\n`);process.exitCode=payload.status==="PASS_DASHBOARD_NULLABLE_ROOT_UPGRADE"?0:2;
}catch{await Promise.all([a?.$disconnect(),b?.$disconnect(),assign?.$disconnect(),ledger?.$disconnect(),reader?.$disconnect()].map(x=>x?.catch(()=>undefined)));const finalCleanup=cleanup();write({status:finalCleanup.ok?"FAIL_SETUP_OR_HARNESS":"FAIL_CLEANUP",startedAt,finishedAt:new Date().toISOString(),environment:"disposable-postgresql-upgrade",mandatoryIds:ids,error:"REDACTED_HARNESS_ERROR",cleanup:finalCleanup,hygiene:{status:"NOT_RUN"},credentialsPersisted:false,productionResourcesTouched:false,rawGucIdentityUsed:false,globalTenantCredentialUsed:false,ownerOrBypassUsedForTenantEvidence:false});process.stderr.write(`Dashboard nullable-root upgrade proof failed; redacted evidence: ${evidenceFile}\n`);process.exitCode=2;}}
void main();
