import { randomBytes } from "node:crypto";
import { chmodSync, readFileSync, writeFileSync } from "node:fs";
import { spawnSync } from "node:child_process";
import { PrismaClient } from "@prisma/client";
import { BrokerDeniedError, TenantAccessBroker } from "../src/lib/tenant-access-broker";
import { TenantBoundPrismaCredentialAuthority, TenantBoundPrismaExecutor, type TenantConnectionProvider } from "../src/lib/tenant-bound-prisma-authority";
import { BeneficiaryRepository } from "../src/lib/beneficiary-repository";
import type { TenantContext } from "../src/lib/tenant-context";

const suffix = `${Date.now()}_${process.pid}`;
const database = `asas_runtime_authority_audit_${suffix}`;
const migrator = `runtime_authority_migrator_${suffix}`;
const controlRole = `runtime_authority_control_${suffix}`;
const tenantA1 = `runtime_authority_a1_${suffix}`;
const tenantA2 = `runtime_authority_a2_${suffix}`;
const tenantB1 = `runtime_authority_b1_${suffix}`;
const evidenceFile = `/tmp/w02-runtime-connection-authority-evidence-${suffix}.json`;
const randomPassword = () => randomBytes(30).toString("base64url");
const passwords = { migrator: randomPassword(), control: randomPassword(), a1: randomPassword(), a2: randomPassword(), b1: randomPassword() };
const orgA = "11111111-1111-4111-8111-111111111111";
const orgB = "22222222-2222-4222-8222-222222222222";
const userA = "aaaaaaaa-0000-4000-8000-000000000001";
const userB = "bbbbbbbb-0000-4000-8000-000000000002";
const membershipA = "aaaaaaaa-0000-4000-8000-000000000101";
const membershipB = "bbbbbbbb-0000-4000-8000-000000000102";
const mandatoryIds = ["A01", "A02", "A03", "A04", "A05", "A06", "A07", "A08", "A09", "A10", "A11", "A12", "A13", "A14", "A15"];
const evidence: Array<Record<string, unknown>> = [];

function run(command: string, args: string[], options: Record<string, unknown> = {}) { return spawnSync(command, args, { encoding: "utf8", ...options }); }
function adminSql(sql: string, db = "postgres") { const out = run("sudo", ["-u", "postgres", "psql", "-d", db, "-X", "-v", "ON_ERROR_STOP=1", "-At"], { input: sql }); if (out.status !== 0) throw new Error("AUDIT_ADMIN_SQL_FAILED"); return out.stdout.trim(); }
function writeEvidence(payload: Record<string, unknown>) { writeFileSync(evidenceFile, `${JSON.stringify(payload, null, 2)}\n`, { mode: 0o600 }); chmodSync(evidenceFile, 0o600); }
function context(input: { organizationId: string; userId: string; membershipId: string; correlationId: string }): TenantContext { return Object.freeze({ ...input, sessionVersion: 1, policySnapshotVersion: 1 }); }
async function record(id: string, expected: string, action: () => Promise<unknown>, check: (actual: unknown) => boolean) { try { const actual = await action(); evidence.push({ id, expected, actual: typeof actual === "string" || typeof actual === "boolean" || typeof actual === "number" ? actual : "REDACTED_OBJECT", result: check(actual) ? "PASS" : "FAIL", timestamp: new Date().toISOString(), environment: "disposable-postgresql-audit", cleanupStatus: "PENDING" }); } catch { evidence.push({ id, expected, actual: "REDACTED_EXCEPTION", result: "FAIL", timestamp: new Date().toISOString(), environment: "disposable-postgresql-audit", cleanupStatus: "PENDING" }); } }
async function denied(action: () => Promise<unknown>, code: string) { try { await action(); return false; } catch (error) { return error instanceof BrokerDeniedError && error.code === code; } }
function cleanup() { const roles = [tenantA1, tenantA2, tenantB1, controlRole, migrator]; const errors: string[] = []; try { adminSql(`SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname='${database}' AND pid <> pg_backend_pid();`); } catch { errors.push("TERMINATE_FAILED"); } try { adminSql(`DROP DATABASE IF EXISTS ${database};`); } catch { errors.push("DROP_DATABASE_FAILED"); } for (const role of roles) try { adminSql(`DROP ROLE IF EXISTS ${role};`); } catch { errors.push("DROP_ROLE_FAILED"); } let residue = ""; try { residue = adminSql(`SELECT datname FROM pg_database WHERE datname='${database}' UNION ALL SELECT rolname FROM pg_roles WHERE rolname IN (${roles.map((role) => `'${role}'`).join(",")});`); } catch { errors.push("RESIDUE_SCAN_FAILED"); } return { ok: errors.length === 0 && residue === "", errors, residueCount: residue ? residue.split("\n").filter(Boolean).length : 0 }; }

async function main() {
  let controlPrisma: PrismaClient | null = null;
  const startedAt = new Date().toISOString();
  try {
    adminSql(`CREATE ROLE ${migrator} LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS PASSWORD '${passwords.migrator}'; CREATE DATABASE ${database} OWNER ${migrator}; CREATE ROLE ${controlRole} LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS PASSWORD '${passwords.control}'; CREATE ROLE ${tenantA1} LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS PASSWORD '${passwords.a1}'; CREATE ROLE ${tenantA2} LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS PASSWORD '${passwords.a2}'; CREATE ROLE ${tenantB1} LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS PASSWORD '${passwords.b1}';`);
    const migrationUrl = `postgresql://${migrator}:${passwords.migrator}@127.0.0.1:5432/${database}?schema=public`;
    if (run("./node_modules/.bin/prisma", ["migrate", "deploy", "--schema", "prisma/schema.prisma"], { env: { ...process.env, DATABASE_URL: migrationUrl } }).status !== 0) throw new Error("MIGRATION_DEPLOY_FAILED");
    adminSql(`GRANT CONNECT ON DATABASE ${database} TO ${controlRole}, ${tenantA1}, ${tenantA2}, ${tenantB1}; GRANT USAGE ON SCHEMA public TO ${controlRole}, ${tenantA1}, ${tenantA2}, ${tenantB1}; GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "organizations", "users", "organization_memberships", "tenant_database_principals", "tenant_access_leases", "tenant_broker_audit_events" TO ${controlRole}; GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "beneficiaries", "beneficiary_documents", "audit_logs" TO ${tenantA1}, ${tenantA2}, ${tenantB1};`, database);
    adminSql(`INSERT INTO "organizations" ("id","name","createdAt","updatedAt") VALUES ('${orgA}','Organization A',now(),now()),('${orgB}','Organization B',now(),now()); INSERT INTO "users" ("id","name","email","role","isActive","authVersion","activeOrganizationId","createdAt","updatedAt") VALUES ('${userA}','User A','a-${suffix}@audit.invalid','MEMBER',true,1,'${orgA}',now(),now()),('${userB}','User B','b-${suffix}@audit.invalid','MEMBER',true,1,'${orgB}',now(),now()); INSERT INTO "organization_memberships" ("id","organizationId","userId","role","isActive","policyVersion","createdAt","updatedAt") VALUES ('${membershipA}','${orgA}','${userA}','MEMBER',true,1,now(),now()),('${membershipB}','${orgB}','${userB}','MEMBER',true,1,now(),now()); INSERT INTO "tenant_database_principals" ("id","organizationId","principalName","credentialReference","generation","status","activatedAt","createdAt","updatedAt") VALUES ('principal-a1','${orgA}','${tenantA1}','audit://runtime/a1',1,'ACTIVE',now(),now(),now()),('principal-b1','${orgB}','${tenantB1}','audit://runtime/b1',1,'ACTIVE',now(),now(),now()); INSERT INTO "beneficiaries" ("id","organizationId","name","phone","status","createdAt","updatedAt") VALUES ('beneficiary-a','${orgA}','Beneficiary A','0500000001','ACTIVE',now(),now()),('beneficiary-b','${orgB}','Beneficiary B','0500000002','ACTIVE',now(),now());`, database);
    controlPrisma = new PrismaClient({ datasources: { db: { url: `postgresql://${controlRole}:${passwords.control}@127.0.0.1:5432/${database}?schema=public` } } });
    const entries = new Map<string, { principalName: string; url: string }>([
      ["audit://runtime/a1", { principalName: tenantA1, url: `postgresql://${tenantA1}:${passwords.a1}@127.0.0.1:5432/${database}?schema=public` }],
      ["audit://runtime/a2", { principalName: tenantA2, url: `postgresql://${tenantA2}:${passwords.a2}@127.0.0.1:5432/${database}?schema=public` }],
      ["audit://runtime/b1", { principalName: tenantB1, url: `postgresql://${tenantB1}:${passwords.b1}@127.0.0.1:5432/${database}?schema=public` }],
    ]);
    const unavailable = new Set<string>(); const usedClients = new Set<PrismaClient>(); let checkoutCount = 0; let discardCount = 0;
    const provider: TenantConnectionProvider = { async checkout(input) { const entry = entries.get(input.credentialReference); if (!entry || unavailable.has(input.credentialReference) || entry.principalName !== input.principalName) throw new Error("AUTHORITY_MAPPING_OR_PROVIDER_UNAVAILABLE"); const prisma = new PrismaClient({ datasources: { db: { url: entry.url } } }); const identity = await prisma.$queryRawUnsafe<Array<{ session_user: string }>>("SELECT session_user"); if (identity[0]?.session_user !== input.principalName) { await prisma.$disconnect(); throw new Error("SESSION_USER_MISMATCH"); } checkoutCount += 1; usedClients.add(prisma); return { prisma, discard: async () => { discardCount += 1; await prisma.$disconnect(); } }; } };
    const authority = new TenantBoundPrismaCredentialAuthority(provider);
    const broker = new TenantAccessBroker(controlPrisma, authority, 5_000);
    const executor = new TenantBoundPrismaExecutor(broker);
    const ctxA = context({ organizationId: orgA, userId: userA, membershipId: membershipA, correlationId: "runtime-authority-a" });
    const ctxB = context({ organizationId: orgB, userId: userB, membershipId: membershipB, correlationId: "runtime-authority-b" });
    const sessionUser = (db: PrismaClient) => db.$queryRawUnsafe<Array<{ session_user: string }>>("SELECT session_user").then((rows) => rows[0]?.session_user);

    await record("A01", "repository without installed tenant authority fails closed", async () => denied(() => new BeneficiaryRepository().list(ctxA, { skip: 0, take: 1 }), "TENANT_CONNECTION_AUTHORITY_UNCONFIGURED"), (actual) => actual === true);
    await record("A02", "A Broker executor hands Prisma authenticated as A tenant login", async () => (await executor.execute(ctxA, sessionUser)) === tenantA1, (actual) => actual === true);
    await record("A03", "B Broker executor hands Prisma authenticated as B tenant login", async () => (await executor.execute(ctxB, sessionUser)) === tenantB1, (actual) => actual === true);
    await record("A04", "sequential A operations receive separate discarded Prisma clients", async () => { const refs: PrismaClient[] = []; await executor.execute(ctxA, async (db) => { refs.push(db); return sessionUser(db); }); await executor.execute(ctxA, async (db) => { refs.push(db); return sessionUser(db); }); return refs.length === 2 && refs[0] !== refs[1] && discardCount >= checkoutCount; }, (actual) => actual === true);
    await record("A05", "concurrent A/B operations preserve distinct client instances and identities", async () => { const refs: PrismaClient[] = []; const [a, b] = await Promise.all([executor.execute(ctxA, async (db) => { refs.push(db); return sessionUser(db); }), executor.execute(ctxB, async (db) => { refs.push(db); return sessionUser(db); })]); return a === tenantA1 && b === tenantB1 && refs.length === 2 && refs[0] !== refs[1]; }, (actual) => actual === true);
    await record("A06", "a consumed lease cannot replay its tenant Prisma operation", async () => { const lease = await broker.issueLease(ctxA); await broker.execute(ctxA, lease, async (input) => input.prisma ? sessionUser(input.prisma) : Promise.reject(new Error("MISSING_PRISMA"))); return denied(() => broker.execute(ctxA, lease, async () => "unexpected"), "LEASE_REPLAY"); }, (actual) => actual === true);
    await record("A07", "expired lease is denied before tenant checkout", async () => { let now = new Date(); const expiring = new TenantAccessBroker(controlPrisma!, authority, 1, () => now); const lease = await expiring.issueLease(ctxB); now = new Date(now.getTime() + 2); return denied(() => expiring.execute(ctxB, lease, async () => "unexpected"), "LEASE_EXPIRED"); }, (actual) => actual === true);
    await record("A08", "revoked lease is denied before tenant checkout", async () => { const lease = await broker.issueLease(ctxB); await broker.revokeLease(lease.leaseId, ctxB.correlationId); return denied(() => broker.execute(ctxB, lease, async () => "unexpected"), "LEASE_REVOKED"); }, (actual) => actual === true);
    await record("A09", "repository writes flow through Broker-bound tenant Prisma with forged org ignored", async () => { const repository = new BeneficiaryRepository(executor); const created = await repository.create(ctxA, { name: "Authority A", phone: "0500000009", status: "ACTIVE", organizationId: orgB } as never); return created.organizationId === orgA; }, (actual) => actual === true);
    await record("A10", "principal rotation changes runtime session_user and retires the old principal", async () => { await controlPrisma!.tenantDatabasePrincipal.update({ where: { id: "principal-a1" }, data: { status: "REVOKED", revokedAt: new Date() } }); await controlPrisma!.tenantDatabasePrincipal.create({ data: { id: "principal-a2", organizationId: orgA, principalName: tenantA2, credentialReference: "audit://runtime/a2", generation: 2, status: "ACTIVE", activatedAt: new Date() } }); return (await executor.execute(ctxA, sessionUser)) === tenantA2; }, (actual) => actual === true);
    await record("A11", "provider outage denies without global Prisma fallback", async () => { unavailable.add("audit://runtime/b1"); const outcome = await denied(() => executor.execute(ctxB, sessionUser), "AUTHORITY_OR_OPERATION_FAILURE"); unavailable.delete("audit://runtime/b1"); return outcome; }, (actual) => actual === true);
    await record("A12", "tenant Prisma transaction rolls back before lease completion on operation failure", async () => { const outcome = await denied(() => executor.execute(ctxA, async (db) => db.$transaction(async (tx) => { await tx.beneficiary.create({ data: { organizationId: orgA, name: "Rollback", phone: "0500000010", status: "ACTIVE" } }); throw new Error("INTENTIONAL_ROLLBACK"); })), "AUTHORITY_OR_OPERATION_FAILURE"); const count = await executor.execute(ctxA, (db) => db.beneficiary.count({ where: { organizationId: orgA, name: "Rollback" } })); return outcome && count === 0; }, (actual) => actual === true);
    await record("A13", "provider reinitialization cannot reuse a consumed pre-restart lease", async () => { const oldLease = await broker.issueLease(ctxA); await broker.execute(ctxA, oldLease, async (input) => input.prisma ? sessionUser(input.prisma) : Promise.reject(new Error("MISSING_PRISMA"))); const restarted = new TenantAccessBroker(controlPrisma!, new TenantBoundPrismaCredentialAuthority(provider), 5_000); const oldDenied = await denied(() => restarted.execute(ctxA, oldLease, async () => "unexpected"), "LEASE_REPLAY"); const currentIdentity = await new TenantBoundPrismaExecutor(restarted).execute(ctxA, sessionUser); return oldDenied && currentIdentity === tenantA2; }, (actual) => actual === true);
    await record("A14", "authority and repository sources contain no GUC, global db import, or DATABASE_URL fallback", async () => { const authoritySource = readFileSync("src/lib/tenant-bound-prisma-authority.ts", "utf8"); const repositorySource = readFileSync("src/lib/beneficiary-repository.ts", "utf8"); return !/(current_setting|set_config|from \"@\/lib\/db\"|DATABASE_URL)/.test(`${authoritySource}\n${repositorySource}`); }, (actual) => actual === true);
    await record("A15", "all audit principals are non-superuser and non-BYPASSRLS", async () => adminSql(`SELECT count(*) FROM pg_roles WHERE rolname IN ('${tenantA1}','${tenantA2}','${tenantB1}','${controlRole}') AND (rolsuper OR rolbypassrls)`, database) === "0", (actual) => actual === true);

    const hardFailures = evidence.filter((item) => item.result !== "PASS").map((item) => item.id);
    const payload: Record<string, unknown> = { status: hardFailures.length === 0 ? "PASS_TENANT_BOUND_RUNTIME_CONNECTION_AUTHORITY" : "FAIL", startedAt, finishedAt: new Date().toISOString(), databaseAlias: database, environment: "disposable-postgresql-audit", mandatoryIds, evidence, hardFailures, cleanup: { ok: false, residueCount: -1 }, credentialsPersisted: false, productionResourcesTouched: false, globalPrismaFallback: false, rawGucUsed: false };
    await controlPrisma.$disconnect(); controlPrisma = null; const finalCleanup = cleanup(); payload.cleanup = finalCleanup; if (!finalCleanup.ok) payload.status = "FAIL_CLEANUP"; for (const item of evidence) item.cleanupStatus = finalCleanup.ok ? "PASS" : "FAIL"; writeEvidence(payload); process.stdout.write(`${JSON.stringify({ status: payload.status, evidenceFile, hardFailures, cleanup: finalCleanup }, null, 2)}\n`); process.exitCode = payload.status === "PASS_TENANT_BOUND_RUNTIME_CONNECTION_AUTHORITY" ? 0 : 2;
  } catch { if (controlPrisma) await controlPrisma.$disconnect().catch(() => undefined); const finalCleanup = cleanup(); writeEvidence({ status: finalCleanup.ok ? "FAIL_SETUP_OR_HARNESS" : "FAIL_CLEANUP", startedAt, finishedAt: new Date().toISOString(), databaseAlias: database, error: "REDACTED_HARNESS_ERROR", mandatoryIds, cleanup: finalCleanup, credentialsPersisted: false, productionResourcesTouched: false }); process.stderr.write(`Runtime connection authority proof failed; redacted evidence: ${evidenceFile}\n`); process.exitCode = 2; }
}
void main();
