import { chmodSync, cpSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { createHash, randomBytes } from "node:crypto";
import { spawnSync } from "node:child_process";
import { PrismaClient } from "@prisma/client";

const suffix = `${Date.now()}_${process.pid}`; const migration = "20260824100000_w02_internal_security_contracts"; const evidenceFile = `/tmp/w02-internal-security-migration-${suffix}.json`; const dbs = [`asas_int_clean_${suffix}`, `asas_int_upgrade_${suffix}`, `asas_int_recovery_${suffix}`]; const roles = [`int_mgr_${suffix}`, `int_a_${suffix}`, `int_b_${suffix}`, `int_none_${suffix}`]; const [migrator, a, b, none] = roles; const secrets = Object.fromEntries(roles.map((role) => [role, randomBytes(30).toString("base64url")])); const orgA = "55555555-5555-4555-8555-555555555555"; const orgB = "66666666-6666-4666-8666-666666666666"; const ids = ["MGR-I01", "MGR-I02", "MGR-I03", "MGR-I04", "MGR-I05", "MGR-I06", "MGR-I07", "MGR-I08"]; const evidence: Array<Record<string, unknown>> = [];
const admin = (statement: string, db = "postgres") => { const result = spawnSync("sudo", ["-u", "postgres", "psql", "-d", db, "-X", "-v", "ON_ERROR_STOP=1", "-At"], { input: statement, encoding: "utf8" }); if (result.status !== 0) throw new Error("AUDIT_ADMIN_SQL_FAILED"); return result.stdout.trim(); };
const url = (db: string, role: string) => `postgresql://${role}:${secrets[role]}@127.0.0.1:5432/${db}?schema=public`;
const deploy = (db: string, schema = "prisma/schema.prisma") => spawnSync("./node_modules/.bin/prisma", ["migrate", "deploy", "--schema", schema], { cwd: process.cwd(), env: { ...process.env, DATABASE_URL: url(db, migrator) }, encoding: "utf8" }).status === 0;
const record = (id: string, expected: string, action: () => boolean) => { try { evidence.push({ id, expected, result: action() ? "PASS" : "FAIL", cleanupStatus: "PENDING" }); } catch { evidence.push({ id, expected, result: "FAIL", actual: "REDACTED_EXCEPTION", cleanupStatus: "PENDING" }); } };
const write = (payload: Record<string, unknown>) => { writeFileSync(evidenceFile, `${JSON.stringify(payload, null, 2)}\n`, { mode: 0o600 }); chmodSync(evidenceFile, 0o600); };
function cleanup() { const errors: string[] = []; for (const db of dbs) try { admin(`SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname='${db}' AND pid <> pg_backend_pid(); DROP DATABASE IF EXISTS ${db} WITH (FORCE);`); } catch { errors.push("DB_CLEANUP_FAILED"); } for (const role of roles) try { admin(`DROP ROLE IF EXISTS ${role};`); } catch { errors.push("ROLE_CLEANUP_FAILED"); } const residue = admin(`SELECT datname FROM pg_database WHERE datname IN (${dbs.map((db) => `'${db}'`).join(",")}) UNION ALL SELECT rolname FROM pg_roles WHERE rolname IN (${roles.map((role) => `'${role}'`).join(",")});`); return { ok: errors.length === 0 && residue === "", errors, residueCount: residue ? residue.split("\n").filter(Boolean).length : 0 }; }
function policyCount(db: string) { return admin("SELECT count(*) FROM pg_class WHERE relname IN ('secret_records','secret_access_audits','privacy_policy_bindings','privacy_requests','activation_records','identity_provider_configs','identity_subject_bindings','identity_provider_callback_states') AND relrowsecurity AND relforcerowsecurity", db); }
async function query(db: string, role: string, statement: string) { const client = new PrismaClient({ datasources: { db: { url: url(db, role) } } }); try { return await client.$queryRawUnsafe<Array<Record<string, unknown>>>(statement); } finally { await client.$disconnect(); } }

async function main() { const startedAt = new Date().toISOString(); let work: string | undefined; try {
  admin(`CREATE ROLE ${migrator} LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS PASSWORD '${secrets[migrator]}'; CREATE ROLE ${a} LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS PASSWORD '${secrets[a]}'; CREATE ROLE ${b} LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS PASSWORD '${secrets[b]}'; CREATE ROLE ${none} LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS PASSWORD '${secrets[none]}';`); for (const db of dbs) admin(`CREATE DATABASE ${db} OWNER ${migrator};`);
  record("MGR-I01", "pristine official deploy applies the internal security migration and eight FORCE RLS tables", () => deploy(dbs[0]) && admin(`SELECT count(*) FROM _prisma_migrations WHERE migration_name='${migration}' AND finished_at IS NOT NULL`, dbs[0]) === "1" && policyCount(dbs[0]) === "8");
  work = mkdtempSync(join(tmpdir(), "w02-internal-pre-")); cpSync("prisma", join(work, "prisma"), { recursive: true }); rmSync(join(work, `prisma/migrations/${migration}`), { recursive: true }); const schema = join(work, "prisma/schema.prisma");
  record("MGR-I02", "pre-WP6 baseline deploy omits only the internal security migration", () => deploy(dbs[1], schema) && admin(`SELECT count(*) FROM _prisma_migrations WHERE migration_name='${migration}'`, dbs[1]) === "0" && policyCount(dbs[1]) === "0");
  cpSync(`prisma/migrations/${migration}`, join(work, `prisma/migrations/${migration}`), { recursive: true });
  record("MGR-I03", "upgrade uses the official forward-only migration and adds all eight RLS policies", () => deploy(dbs[1], schema) && admin(`SELECT count(*) FROM _prisma_migrations WHERE migration_name='${migration}' AND finished_at IS NOT NULL`, dbs[1]) === "1" && policyCount(dbs[1]) === "8");
  admin(`GRANT CONNECT ON DATABASE ${dbs[1]} TO ${a},${b},${none}; GRANT USAGE ON SCHEMA public,security TO ${a},${b},${none}; GRANT EXECUTE ON FUNCTION security.current_session_organization_id() TO ${a},${b},${none}; GRANT SELECT,INSERT,UPDATE,DELETE ON "organizations","secret_records" TO ${a},${b},${none}; INSERT INTO "organizations" ("id","name","createdAt","updatedAt") VALUES ('${orgA}','A',now(),now()),('${orgB}','B',now(),now()); INSERT INTO security.role_to_organization (role_oid,organization_id) VALUES ('${a}'::regrole::oid,'${orgA}'),('${b}'::regrole::oid,'${orgB}'); INSERT INTO "secret_records" ("id","organizationId","providerKey","purpose","opaqueReference","keyVersion","createdById","createdAt","updatedAt") VALUES ('secret-a','${orgA}','fixture','read','secretref:upgrade-a-0001','v1','actor-a',now(),now()),('secret-b','${orgB}','fixture','read','secretref:upgrade-b-0001','v1','actor-b',now(),now());`, dbs[1]);
  record("MGR-I04", "upgraded A/B sessions see only their own secret references", () => false); const aRows = await query(dbs[1], a, 'SELECT id FROM "secret_records" ORDER BY id'); const bRows = await query(dbs[1], b, 'SELECT id FROM "secret_records" ORDER BY id'); evidence.at(-1)!.result = aRows.length === 1 && aRows[0].id === "secret-a" && bRows.length === 1 && bRows[0].id === "secret-b" ? "PASS" : "FAIL";
  record("MGR-I05", "unmapped role and cross-tenant row insert fail closed after upgrade", () => false); const noneRows = await query(dbs[1], none, 'SELECT id FROM "secret_records"'); let denied = false; try { await query(dbs[1], a, `INSERT INTO "secret_records" ("id","organizationId","providerKey","purpose","opaqueReference","keyVersion","createdById","createdAt","updatedAt") VALUES ('denied','${orgB}','x','x','secretref:cross-0001','v1','actor',now(),now())`); } catch { denied = true; } evidence.at(-1)!.result = noneRows.length === 0 && denied ? "PASS" : "FAIL";
  record("MGR-I06", "migration source hash is unchanged through upgrade and forbids raw GUC identity", () => createHash("sha256").update(readFileSync(`prisma/migrations/${migration}/migration.sql`)).digest("hex") === createHash("sha256").update(readFileSync(join(work!, `prisma/migrations/${migration}/migration.sql`))).digest("hex") && !/current_setting|set_config/.test(readFileSync(`prisma/migrations/${migration}/migration.sql`, "utf8")) && admin("SELECT count(*) FROM _prisma_migrations WHERE rolled_back_at IS NOT NULL", dbs[1]) === "0");
  record("MGR-I07", "recovery is discard/rebuild with clean official deploy, not historical rollback", () => deploy(dbs[2]) && policyCount(dbs[2]) === "8");
  record("MGR-I08", "mandatory IDs are exact and prior gates are all recorded", () => ids.slice(0, -1).every((id) => evidence.some((entry) => entry.id === id)) && new Set(evidence.map((entry) => entry.id)).size === evidence.length);
  rmSync(work, { recursive: true, force: true }); work = undefined; const clean = cleanup(); for (const item of evidence) item.cleanupStatus = clean.ok ? "PASS" : "FAIL"; const status = evidence.length === ids.length && evidence.every((item) => item.result === "PASS") && clean.ok ? "PASS_W02_INTERNAL_SECURITY_MIGRATION_REHEARSAL" : "FAIL"; write({ status, startedAt, finishedAt: new Date().toISOString(), environment: "disposable-postgresql-audit", mandatoryIds: ids, evidence, cleanup: clean, credentialsPersisted: false, productionResourcesTouched: false, rawGucIdentityUsed: false, rollbackClaim: "No production rollback: disposable upgrade databases are discarded and rebuilt by official forward migrations." }); process.stdout.write(`${JSON.stringify({ status, evidenceFile, cleanup: clean }, null, 2)}\n`); process.exitCode = status === "PASS_W02_INTERNAL_SECURITY_MIGRATION_REHEARSAL" ? 0 : 2;
} catch { if (work) rmSync(work, { recursive: true, force: true }); const clean = cleanup(); write({ status: clean.ok ? "FAIL_SETUP_OR_HARNESS" : "FAIL_CLEANUP", startedAt, finishedAt: new Date().toISOString(), environment: "disposable-postgresql-audit", mandatoryIds: ids, evidence, cleanup: clean, credentialsPersisted: false, productionResourcesTouched: false, rawGucIdentityUsed: false }); process.exitCode = 2; } }
void main();
