import { chmodSync, readFileSync, writeFileSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { randomBytes, randomUUID } from "node:crypto";
import { PrismaClient } from "@prisma/client";
import { PrivateArtifactRepository, TenantArtifactBoundaryError, type TenantArtifactProvider } from "../src/lib/private-artifact";
import { TenantAccessBroker, type TenantCredentialAuthority } from "../src/lib/tenant-access-broker";
import { TenantBoundPrismaCredentialAuthority, TenantBoundPrismaExecutor, installTenantBoundPrismaExecutor, type TenantConnectionProvider } from "../src/lib/tenant-bound-prisma-authority";
import type { TenantContext } from "../src/lib/tenant-context";

type Evidence = Record<string, unknown>;
const mandatoryIds = ["S01", "S02", "S03", "S04", "S05", "S06", "S07", "S08", "S09", "S10"];
const suffix = `${Date.now()}_${randomBytes(4).toString("hex")}`;
const database = `w02_storage_${suffix}`.replace(/[^a-z0-9_]/gi, "_");
const roles = { migrator: `w02sm_${suffix}`, control: `w02sc_${suffix}`, a1: `w02sa_${suffix}`, a2: `w02sa2_${suffix}`, b1: `w02sb_${suffix}` };
const passwords = Object.fromEntries(Object.keys(roles).map((key) => [roles[key as keyof typeof roles], randomBytes(24).toString("base64url")]));
const evidenceFile = `/tmp/w02-storage-evidence-${suffix}.json`;
const evidence: Evidence[] = [];
const start = new Date().toISOString();

function admin(sql: string, databaseName?: string) { return execFileSync("sudo", ["-u", "postgres", "psql", "-v", "ON_ERROR_STOP=1", "-At", ...(databaseName ? ["-d", databaseName] : []), "-c", sql], { encoding: "utf8" }).trim(); }
function quoted(value: string) { return `"${value.replaceAll('"', '""')}"`; }
function dbUrl(role: string) { return `postgresql://${role}:${passwords[role]}@127.0.0.1:5432/${database}?schema=public`; }
function run(command: string, args: string[], env: NodeJS.ProcessEnv = process.env) { try { execFileSync(command, args, { cwd: process.cwd(), env, stdio: "pipe" }); return true; } catch { return false; } }
function write(payload: Record<string, unknown>) { writeFileSync(evidenceFile, `${JSON.stringify(payload, null, 2)}\n`, { mode: 0o600 }); chmodSync(evidenceFile, 0o600); }
async function denied(action: () => Promise<unknown>) { try { await action(); return false; } catch { return true; } }
async function waitFor(check: () => Promise<boolean>, attempts = 40) { for (let i = 0; i < attempts; i += 1) { if (await check()) return true; await new Promise((resolve) => setTimeout(resolve, 25)); } return false; }
function ctx(organizationId: string, userId: string, membershipId: string, correlationId: string, policySnapshotVersion = 1): TenantContext { return Object.freeze({ organizationId, userId, membershipId, sessionVersion: 1, policySnapshotVersion, correlationId }); }
function cleanup() { const errors: string[] = []; try { admin(`DROP DATABASE IF EXISTS ${quoted(database)} WITH (FORCE);`); } catch { errors.push("DATABASE"); } for (const role of Object.values(roles)) { try { admin(`DROP ROLE IF EXISTS ${quoted(role)};`); } catch { errors.push("ROLE"); } } return { ok: errors.length === 0, errors, residueCount: errors.length }; }

class MemoryArtifactProvider implements TenantArtifactProvider {
  readonly objects = new Map<string, { organizationId: string; artifactId: string; data: Uint8Array }>();
  readonly deliveries = new Map<string, { objectKey: string; expiresAt: Date }>();
  readonly observations: Array<{ organizationId: string; artifactId: string; action: string }> = [];
  available = true;
  async put(input: Readonly<{ organizationId: string; artifactId: string; objectKey: string; data: Uint8Array; contentType: string }>) { if (!this.available) throw new Error("ARTIFACT_PROVIDER_UNAVAILABLE"); if (!input.objectKey.startsWith(`private/${input.organizationId}/artifact/${input.artifactId}/v`)) throw new Error("ARTIFACT_PROVIDER_KEY_INVALID"); this.objects.set(input.objectKey, { organizationId: input.organizationId, artifactId: input.artifactId, data: input.data }); this.observations.push({ organizationId: input.organizationId, artifactId: input.artifactId, action: "PUT" }); }
  async delete(input: Readonly<{ organizationId: string; artifactId: string; objectKey: string }>) { if (!this.available) throw new Error("ARTIFACT_PROVIDER_UNAVAILABLE"); const object = this.objects.get(input.objectKey); if (object && (object.organizationId !== input.organizationId || object.artifactId !== input.artifactId)) throw new Error("ARTIFACT_PROVIDER_SCOPE_DENIED"); this.objects.delete(input.objectKey); this.observations.push({ organizationId: input.organizationId, artifactId: input.artifactId, action: "DELETE" }); }
  async issueDelivery(input: Readonly<{ organizationId: string; artifactId: string; objectKey: string; expiresInSeconds: number }>) { if (!this.available) throw new Error("ARTIFACT_PROVIDER_UNAVAILABLE"); const object = this.objects.get(input.objectKey); if (!object || object.organizationId !== input.organizationId || object.artifactId !== input.artifactId) throw new Error("ARTIFACT_PROVIDER_SCOPE_DENIED"); const delivery = `delivery-${randomUUID()}`; const expiresAt = new Date(Date.now() + input.expiresInSeconds * 1000); this.deliveries.set(delivery, { objectKey: input.objectKey, expiresAt }); this.observations.push({ organizationId: input.organizationId, artifactId: input.artifactId, action: "DELIVERY" }); return { delivery, expiresAt }; }
  resolves(delivery: string, now = new Date()) { const entry = this.deliveries.get(delivery); return Boolean(entry && entry.expiresAt > now && this.objects.has(entry.objectKey)); }
}

async function record(id: string, expected: string, action: () => Promise<boolean>) { try { const actual = await action(); evidence.push({ id, expected, actual, result: actual ? "PASS" : "FAIL", timestamp: new Date().toISOString(), environment: "disposable-postgresql-memory-artifact-audit", cleanupStatus: "PENDING" }); } catch (error) { const message = error instanceof Error ? error.message : ""; const exceptionCategory = /permission denied/i.test(message) ? "POSTGRES_PERMISSION_DENIED" : /row-level security/i.test(message) ? "POSTGRES_RLS_DENIED" : /foreign key/i.test(message) ? "POSTGRES_FOREIGN_KEY" : /unique constraint/i.test(message) ? "POSTGRES_UNIQUE" : /STALE_|MEMBERSHIP_|TENANT_ARTIFACT_|ARTIFACT_PROVIDER_/i.test(message) ? "EXPECTED_BOUNDARY" : "REDACTED"; evidence.push({ id, expected, actual: "REDACTED_EXCEPTION", exceptionCategory, result: "FAIL", timestamp: new Date().toISOString(), environment: "disposable-postgresql-memory-artifact-audit", cleanupStatus: "PENDING" }); } }

async function main() {
  let control: PrismaClient | undefined;
  const tenantClients: PrismaClient[] = [];
  const provider = new MemoryArtifactProvider();
  try {
    for (const role of Object.values(roles)) admin(`CREATE ROLE ${quoted(role)} LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS PASSWORD '${passwords[role]}';`);
    admin(`CREATE DATABASE ${quoted(database)} OWNER ${quoted(roles.migrator)};`);
    if (!run("./node_modules/.bin/prisma", ["migrate", "deploy", "--schema", "prisma/schema.prisma"], { ...process.env, DATABASE_URL: dbUrl(roles.migrator) })) throw new Error("MIGRATION_DEPLOY_FAILED");
    admin(`GRANT CONNECT ON DATABASE ${quoted(database)} TO ${quoted(roles.control)}, ${quoted(roles.a1)}, ${quoted(roles.a2)}, ${quoted(roles.b1)}; GRANT USAGE ON SCHEMA public, security TO ${quoted(roles.control)}, ${quoted(roles.a1)}, ${quoted(roles.a2)}, ${quoted(roles.b1)}; GRANT EXECUTE ON FUNCTION security.current_session_organization_id() TO ${quoted(roles.control)}, ${quoted(roles.a1)}, ${quoted(roles.a2)}, ${quoted(roles.b1)}; GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "organizations", "users", "organization_memberships", "organization_roles", "organization_role_permissions", "membership_roles", "permissions", "tenant_database_principals", "tenant_access_leases", "tenant_broker_audit_events" TO ${quoted(roles.control)}; GRANT SELECT ON TABLE "organization_memberships", "organization_roles", "organization_role_permissions", "membership_roles", "membership_permission_overrides", "permissions" TO ${quoted(roles.a1)}, ${quoted(roles.a2)}, ${quoted(roles.b1)}; GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "beneficiaries", "documents", "private_artifacts", "audit_logs" TO ${quoted(roles.a1)}, ${quoted(roles.a2)}, ${quoted(roles.b1)};`, database);
    const orgA = "storage-org-a", orgB = "storage-org-b", userA = "storage-user-a", userB = "storage-user-b", userC = "storage-user-c", membershipA = "storage-membership-a", membershipB = "storage-membership-b", membershipC = "storage-membership-c", beneficiaryA = "storage-beneficiary-a", beneficiaryB = "storage-beneficiary-b";
    const permissionRows = ["document.private.read", "document.private.upload", "document.private.manage"].map((name, index) => `('storage-perm-${index}','${name}','document','${name.split(".").at(-1)}')`).join(",");
    admin(`INSERT INTO "organizations" ("id","name","createdAt","updatedAt") VALUES ('${orgA}','Storage A',now(),now()),('${orgB}','Storage B',now(),now()); INSERT INTO "users" ("id","name","email","role","isActive","authVersion","createdAt","updatedAt") VALUES ('${userA}','A','a-${suffix}@audit.invalid','MEMBER',true,1,now(),now()),('${userB}','B','b-${suffix}@audit.invalid','MEMBER',true,1,now(),now()),('${userC}','C','c-${suffix}@audit.invalid','MEMBER',true,1,now(),now()); INSERT INTO "organization_memberships" ("id","organizationId","userId","role","isActive","policyVersion","createdAt","updatedAt") VALUES ('${membershipA}','${orgA}','${userA}','MEMBER',true,1,now(),now()),('${membershipB}','${orgB}','${userB}','MEMBER',true,1,now(),now()),('${membershipC}','${orgA}','${userC}','MEMBER',true,1,now(),now()); INSERT INTO "permissions" ("id","name","module","action") VALUES ${permissionRows}; INSERT INTO "organization_roles" ("id","organizationId","name","isSystem","createdAt","updatedAt") VALUES ('storage-role-a','${orgA}','STORAGE_ADMIN',true,now(),now()),('storage-role-b','${orgB}','STORAGE_ADMIN',true,now(),now()); INSERT INTO "organization_role_permissions" ("organizationRoleId","permissionId","effect") SELECT 'storage-role-a',id,'ALLOW' FROM "permissions" WHERE name LIKE 'document.private.%'; INSERT INTO "organization_role_permissions" ("organizationRoleId","permissionId","effect") SELECT 'storage-role-b',id,'ALLOW' FROM "permissions" WHERE name LIKE 'document.private.%'; INSERT INTO "membership_roles" ("membershipId","organizationRoleId","assignedAt") VALUES ('${membershipA}','storage-role-a',now()),('${membershipB}','storage-role-b',now()),('${membershipC}','storage-role-a',now()); INSERT INTO "beneficiaries" ("id","organizationId","name","phone","status","createdAt","updatedAt") VALUES ('${beneficiaryA}','${orgA}','A','0500000001','ACTIVE',now(),now()),('${beneficiaryB}','${orgB}','B','0500000002','ACTIVE',now(),now()); INSERT INTO security.role_to_organization (role_oid,organization_id) VALUES ('${roles.a1}'::regrole::oid,'${orgA}'),('${roles.b1}'::regrole::oid,'${orgB}'); INSERT INTO "tenant_database_principals" ("id","organizationId","principalName","credentialReference","generation","status","activatedAt","createdAt","updatedAt") VALUES ('storage-principal-a1','${orgA}','${roles.a1}','audit://storage/a1',1,'ACTIVE',now(),now(),now()),('storage-principal-b1','${orgB}','${roles.b1}','audit://storage/b1',1,'ACTIVE',now(),now(),now());`, database);
    control = new PrismaClient({ datasources: { db: { url: dbUrl(roles.control) } } });
    const sessionObservations: Array<{ principal: string; correlationId: string }> = [];
    const connectionProvider: TenantConnectionProvider = { async checkout(input) { const client = new PrismaClient({ datasources: { db: { url: dbUrl(input.principalName) } } }); tenantClients.push(client); const rows = await client.$queryRawUnsafe<Array<{ session_user: string }>>("SELECT session_user"); if (rows[0]?.session_user !== input.principalName) { await client.$disconnect(); throw new Error("STORAGE_SESSION_USER_MISMATCH"); } sessionObservations.push({ principal: rows[0].session_user, correlationId: input.correlationId }); return { prisma: client, discard: async () => { await client.$disconnect(); } }; } };
    const authority: TenantCredentialAuthority = new TenantBoundPrismaCredentialAuthority(connectionProvider);
    const broker = new TenantAccessBroker(control, authority);
    const executor = new TenantBoundPrismaExecutor(broker);
    installTenantBoundPrismaExecutor(executor);
    const repository = new PrivateArtifactRepository(executor, provider);
    const contextA = ctx(orgA, userA, membershipA, "storage-a"), contextB = ctx(orgB, userB, membershipB, "storage-b"), contextC = ctx(orgA, userC, membershipC, "storage-c");
    let artifactA = "", artifactB = "";
    await record("S01", "Server derives a private A object key, persists tenant metadata, and never returns a public URL", async () => { const result = await repository.create(contextA, { name: "A.pdf", contentType: "application/pdf", size: 3, data: new Uint8Array([1, 2, 3]), beneficiaryId: beneficiaryA }); artifactA = result.artifactId; const listed = await repository.list(contextA); const object = [...provider.objects.entries()].find(([key]) => key.includes(artifactA)); return listed.length === 1 && Boolean(object) && object![0].startsWith(`private/${orgA}/artifact/${artifactA}/v1`) && !JSON.stringify(result).includes("http"); });
    await record("S02", "A/B listing and delivery remain isolated by metadata ownership and per-tenant session_user", async () => { const result = await repository.create(contextB, { name: "B.pdf", contentType: "application/pdf", size: 2, data: new Uint8Array([4, 5]), beneficiaryId: beneficiaryB }); artifactB = result.artifactId; const [a, b] = await Promise.all([repository.list(contextA), repository.list(contextB)]); return a.length === 1 && b.length === 1 && a[0]?.id === artifactA && b[0]?.id === artifactB && sessionObservations.some((entry) => entry.principal === roles.a1) && sessionObservations.some((entry) => entry.principal === roles.b1); });
    await record("S03", "Foreign artifact guessed by B cannot download, replace, or delete A data", async () => { const before = provider.objects.size; const [download, replace, remove] = await Promise.all([denied(() => repository.issueDownload(contextB, artifactA)), denied(() => repository.replace(contextB, artifactA, { contentType: "application/pdf", size: 1, data: new Uint8Array([9]) })), denied(() => repository.delete(contextB, artifactA))]); return download && replace && remove && provider.objects.size === before; });
    await record("S04", "Foreign beneficiary reference and caller-supplied path authority fail closed before provider write", async () => { const before = provider.objects.size; const foreignOwner = await denied(() => repository.create(contextA, { name: "forged.pdf", contentType: "application/pdf", size: 1, data: new Uint8Array([7]), beneficiaryId: beneficiaryB })); const source = readFileSync("src/lib/private-artifact.ts", "utf8"); return foreignOwner && provider.objects.size === before && !source.includes("objectKey: input") && !source.includes("getPublicUrl"); });
    await record("S05", "Opaque short-lived delivery requires owned artifact and expires at provider boundary", async () => { const issued = await repository.issueDownload(contextA, artifactA); return issued.delivery.startsWith("delivery-") && !issued.delivery.includes("http") && provider.resolves(issued.delivery) && !provider.resolves(issued.delivery, new Date(issued.expiresAt.getTime() + 1)); });
    await record("S06", "Stale policy and revoked membership fail closed before artifact delivery", async () => { await control!.organizationMembership.update({ where: { id: membershipA }, data: { policyVersion: 2 } }); const stale = await denied(() => repository.issueDownload(contextA, artifactA)); const freshA = ctx(orgA, userA, membershipA, "storage-a-fresh", 2); await control!.organizationMembership.update({ where: { id: membershipA }, data: { isActive: false } }); const revoked = await denied(() => repository.issueDownload(freshA, artifactA)); return stale && revoked; });
    await record("S07", "Replace rotates immutable key/version and delete revokes future delivery", async () => { const before = [...provider.objects.keys()].find((key) => key.includes(artifactB)); const replaced = await repository.replace(contextB, artifactB, { contentType: "application/pdf", size: 4, data: new Uint8Array([6, 6, 6, 6]) }); const after = [...provider.objects.keys()].find((key) => key.includes(artifactB)); const deleted = await repository.delete(contextB, artifactB); const later = await denied(() => repository.issueDownload(contextB, artifactB)); return replaced.version === 2 && before !== after && !provider.objects.has(before ?? "") && deleted && later; });
    await record("S08", "Provider outage rejects upload without metadata or object fallback", async () => { provider.available = false; const before = (await repository.list(contextB)).length; const unavailable = await denied(() => repository.create(contextB, { name: "outage.pdf", contentType: "application/pdf", size: 1, data: new Uint8Array([8]) })); provider.available = true; const after = (await repository.list(contextB)).length; return unavailable && before === after; });
    await record("S09", "Parallel A/B uploads use distinct tenant keys and clients with no shared object namespace", async () => { const parallelA = ctx(orgA, userC, membershipC, "storage-parallel-a"); const parallelB = ctx(orgB, userB, membershipB, "storage-parallel-b"); const [a, b] = await Promise.all([repository.create(parallelA, { name: "parallel-a.pdf", contentType: "application/pdf", size: 1, data: new Uint8Array([1]) }), repository.create(parallelB, { name: "parallel-b.pdf", contentType: "application/pdf", size: 1, data: new Uint8Array([2]) })]); const keys = [...provider.objects.keys()].filter((key) => key.includes(a.artifactId) || key.includes(b.artifactId)); return keys.length === 2 && keys.some((key) => key.startsWith(`private/${orgA}/`)) && keys.some((key) => key.startsWith(`private/${orgB}/`)) && a.artifactId !== b.artifactId; });
    await record("S10", "Source, role, audit, discard, cleanup, and hygiene checks remain safe", async () => { const sources = ["src/lib/private-artifact.ts", "src/lib/storage.ts", "src/app/api/upload/route.ts", "src/app/api/documents/route.ts", "src/app/api/documents/[id]/route.ts"].map((file) => readFileSync(file, "utf8")).join("\n"); const unsafe = admin(`SELECT count(*) FROM pg_roles WHERE rolname IN ('${roles.a1}','${roles.a2}','${roles.b1}') AND (rolsuper OR rolbypassrls OR rolcreaterole);`); const auditCount = await new TenantBoundPrismaExecutor(broker).execute(contextC, (db) => db.auditLog.count({ where: { organizationId: orgA, entity: "PrivateArtifact" } })); return !/current_setting|set_config|S3_SECRET_KEY|minioadmin|getPublicUrl/.test(sources) && unsafe === "0" && auditCount >= 2 && sessionObservations.length > 0; });
    for (const client of tenantClients.splice(0)) await client.$disconnect().catch(() => undefined); await control.$disconnect(); control = undefined;
    const finalCleanup = cleanup(); for (const item of evidence) item.cleanupStatus = finalCleanup.ok ? "PASS" : "FAIL";
    const payload: Record<string, unknown> = { status: "PENDING", startedAt: start, finishedAt: new Date().toISOString(), databaseAlias: database, environment: "disposable-postgresql-memory-artifact-audit", mandatoryIds, evidence, hardFailures: [], cleanup: finalCleanup, hygiene: { status: "PENDING" }, credentialsPersisted: false, productionResourcesTouched: false, rawGucIdentityUsed: false, globalPrismaFallback: false, ownerOrBypassUsedForTenantEvidence: false, provider: "memory-only-test-double" };
    write(payload); const hygiene = run("node", ["scripts/w02-audit-artifact-hygiene-scan.mjs"]); payload.hygiene = { status: hygiene ? "PASS_AUDIT_ARTIFACT_HYGIENE_SCAN" : "FAIL_AUDIT_ARTIFACT_HYGIENE_SCAN" }; const failed = evidence.filter((item) => item.result !== "PASS").map((item) => item.id); payload.hardFailures = failed; payload.status = finalCleanup.ok && hygiene && failed.length === 0 ? "PASS_STORAGE_RUNTIME" : "FAIL"; write(payload); process.stdout.write(`${JSON.stringify({ status: payload.status, evidenceFile, hardFailures: failed, cleanup: finalCleanup, hygiene: payload.hygiene }, null, 2)}\n`); process.exitCode = payload.status === "PASS_STORAGE_RUNTIME" ? 0 : 2;
  } catch { for (const client of tenantClients.splice(0)) await client.$disconnect().catch(() => undefined); if (control) await control.$disconnect().catch(() => undefined); const finalCleanup = cleanup(); write({ status: finalCleanup.ok ? "FAIL_SETUP_OR_HARNESS" : "FAIL_CLEANUP", startedAt: start, finishedAt: new Date().toISOString(), databaseAlias: database, error: "REDACTED_HARNESS_ERROR", mandatoryIds, evidence, cleanup: finalCleanup, hygiene: { status: "NOT_RUN" }, credentialsPersisted: false, productionResourcesTouched: false, rawGucIdentityUsed: false, globalPrismaFallback: false, ownerOrBypassUsedForTenantEvidence: false, provider: "memory-only-test-double" }); process.stderr.write(`Storage runtime proof failed; redacted evidence: ${evidenceFile}\n`); process.exitCode = 2; }
}

void main();
