import { createHash, randomBytes, randomUUID } from "node:crypto";
import { chmodSync, writeFileSync } from "node:fs";
import { spawnSync } from "node:child_process";
import { PrismaClient } from "@prisma/client";

/** ADR-W02-010/011/012 clean PostgreSQL proof; no production connection or RLS financial policy. */
const suffix = `${Date.now()}_${process.pid}`;
const database = `asas_dashboard_root_audit_${suffix}`;
const role = (label: string) => `dashboard_root_${label}_${suffix}`;
const migrator = role("migrator"), securityOwner = role("security_owner"), assignmentWriter = role("assignment_writer"), ledgerWriter = role("ledger_writer"), readerRole = role("reader"), tenantA = role("tenant_a"), tenantB = role("tenant_b");
const evidenceFile = `/tmp/w02-dashboard-nullable-root-evidence-${suffix}.json`;
const ids = ["NR01","NR02","NR03","NR04","NR05","NR06","NR07","NR08","NR09","NR10","NR11","NR12","NR13","NR14","NR15"];
const pw = () => randomBytes(30).toString("base64url");
const secret = { migrator: pw(), assignment: pw(), ledger: pw(), reader: pw(), a: pw(), b: pw() };
const orgA = "11111111-1111-4111-8111-111111111111";
const orgB = "22222222-2222-4222-8222-222222222222";
const userA = "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa";
const userB = "bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb";
const evidence: Array<Record<string, unknown>> = [];
const diagnostics: Array<{ id: string; error: string }> = [];

function run(file: string, args: string[], options: Record<string, unknown> = {}) { return spawnSync(file, args, { encoding: "utf8", ...options }); }
function admin(sql: string, db = "postgres") { const result = run("sudo", ["-u","postgres","psql","-d",db,"-X","-v","ON_ERROR_STOP=1","-At"], { input: sql }); if (result.status !== 0) throw new Error("REDACTED_ADMIN_SETUP_ERROR"); return result.stdout.trim(); }
function url(name: string, password: string) { return `postgresql://${name}:${password}@127.0.0.1:5432/${database}?schema=public`; }
function write(payload: Record<string, unknown>) { writeFileSync(evidenceFile, `${JSON.stringify(payload,null,2)}\n`, { mode: 0o600 }); chmodSync(evidenceFile,0o600); }
async function denied(action: () => Promise<unknown>) { try { await action(); return false; } catch { return true; } }
async function record(id: string, expected: string, action: () => Promise<boolean>) { let actual = false; try { actual = await action(); } catch (error) { actual = false; const message = error instanceof Error ? error.message : "REDACTED_ASSERTION_ERROR"; diagnostics.push({ id, error: message.replace(/postgresql:\/\/[^\s]+/gi, "postgresql://[REDACTED]").replace(/PASSWORD\s+'[^']+'/gi, "PASSWORD '[REDACTED]'").slice(0, 280) }); } evidence.push({ id, expected, actual, result: actual ? "PASS" : "FAIL", environment: "disposable-postgresql-audit", cleanupStatus: "PENDING" }); }
function cleanup() { const roles=[tenantA,tenantB,readerRole,ledgerWriter,assignmentWriter,securityOwner,migrator], errors:string[]=[]; try{admin(`SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname='${database}' AND pid <> pg_backend_pid();`)}catch{errors.push("TERMINATE_FAILED")} try{admin(`DROP DATABASE IF EXISTS ${database};`)}catch{errors.push("DROP_DATABASE_FAILED")} for(const item of roles)try{admin(`DROP ROLE IF EXISTS ${item};`)}catch{errors.push("DROP_ROLE_FAILED")} let residue="";try{residue=admin(`SELECT datname FROM pg_database WHERE datname='${database}' UNION ALL SELECT rolname FROM pg_roles WHERE rolname IN (${roles.map((item)=>`'${item}'`).join(",")});`)}catch{errors.push("RESIDUE_SCAN_FAILED")} return {ok:errors.length===0&&residue==="",errors,residueCount:residue?residue.split("\n").filter(Boolean).length:0}; }

async function main() {
  let a: PrismaClient|undefined,b: PrismaClient|undefined,assignment: PrismaClient|undefined,ledger: PrismaClient|undefined,reader: PrismaClient|undefined;
  const startedAt = new Date().toISOString();
  try {
    admin(`CREATE ROLE ${migrator} LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS PASSWORD '${secret.migrator}'; CREATE DATABASE ${database} OWNER ${migrator}; CREATE ROLE ${securityOwner} NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS; CREATE ROLE ${assignmentWriter} LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS PASSWORD '${secret.assignment}'; CREATE ROLE ${ledgerWriter} LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS PASSWORD '${secret.ledger}'; CREATE ROLE ${readerRole} LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS PASSWORD '${secret.reader}'; CREATE ROLE ${tenantA} LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS PASSWORD '${secret.a}'; CREATE ROLE ${tenantB} LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS PASSWORD '${secret.b}';`);
    const deploy = run("./node_modules/.bin/prisma",["migrate","deploy","--schema","prisma/schema.prisma"],{env:{...process.env,DATABASE_URL:url(migrator,secret.migrator)}}); if(deploy.status!==0) throw new Error("MIGRATION_DEPLOY_FAILED");
    admin(`ALTER FUNCTION control.apply_member_backfill_assignment(text) OWNER TO ${securityOwner}; ALTER FUNCTION control.apply_kpi_backfill_assignment(text) OWNER TO ${securityOwner}; GRANT USAGE ON SCHEMA security, control TO ${securityOwner}; GRANT SELECT ON security.role_to_organization TO ${securityOwner}; GRANT SELECT ON control.nullable_root_backfill_assignments TO ${securityOwner}; GRANT SELECT("id","organizationId") ON "members", "kpis" TO ${securityOwner}; GRANT SELECT("kpiId","organizationId") ON "kpi_records" TO ${securityOwner}; GRANT UPDATE("organizationId") ON "members", "kpis", "kpi_records" TO ${securityOwner}; INSERT INTO "organizations" ("id","name","createdAt","updatedAt") VALUES ('${orgA}','Organization A',now(),now()),('${orgB}','Organization B',now(),now()); INSERT INTO "users" ("id","name","email","role","isActive","authVersion","activeOrganizationId","createdAt","updatedAt") VALUES ('${userA}','User A','a-${suffix}@audit.invalid','MEMBER',true,1,'${orgA}',now(),now()),('${userB}','User B','b-${suffix}@audit.invalid','MEMBER',true,1,'${orgB}',now(),now()); INSERT INTO security.role_to_organization(role_oid,organization_id) VALUES ('${tenantA}'::regrole::oid,'${orgA}'),('${tenantB}'::regrole::oid,'${orgB}'); INSERT INTO "members" ("id","userId","status","createdAt","updatedAt") VALUES ('member-a','${userA}','ACTIVE',now(),now()),('member-b','${userB}','ACTIVE',now(),now()); INSERT INTO "kpis" ("id","title","targetEntity","unit","targetValue","status","createdAt","updatedAt") VALUES ('kpi-a','KPI A','PROJECT','% ',100,'ACTIVE',now(),now()),('kpi-b','KPI B','PROJECT','% ',100,'ACTIVE',now(),now()); INSERT INTO "kpi_records" ("id","kpiId","period","actualValue","targetValue","percent","createdAt","updatedAt") VALUES ('record-a','kpi-a','2026-01',10,100,10,now(),now()),('record-b','kpi-b','2026-01',20,100,20,now(),now()); GRANT USAGE ON SCHEMA public, security, control TO ${tenantA}, ${tenantB}, ${assignmentWriter}, ${ledgerWriter}, ${readerRole}; GRANT EXECUTE ON FUNCTION control.apply_member_backfill_assignment(text), control.apply_kpi_backfill_assignment(text) TO ${tenantA},${tenantB}; GRANT INSERT ON control.nullable_root_backfill_assignments TO ${assignmentWriter}; GRANT INSERT ON control.backfill_audit_ledger TO ${ledgerWriter}; GRANT SELECT ON control.backfill_audit_ledger, control.nullable_root_backfill_assignments, "members", "kpis", "kpi_records" TO ${readerRole};`,database);
    a=new PrismaClient({datasources:{db:{url:url(tenantA,secret.a)}}}); b=new PrismaClient({datasources:{db:{url:url(tenantB,secret.b)}}}); assignment=new PrismaClient({datasources:{db:{url:url(assignmentWriter,secret.assignment)}}}); ledger=new PrismaClient({datasources:{db:{url:url(ledgerWriter,secret.ledger)}}}); reader=new PrismaClient({datasources:{db:{url:url(readerRole,secret.reader)}}});
    const digest=createHash("sha256").update("redacted-dashboard-manifest-v1").digest("hex"), operationA=randomUUID(),operationB=randomUUID();
    const ledgerEvent=(operationId:string,attempt:number,phase:"STARTED"|"SUCCEEDED"|"FAILED"|"ROLLBACK",organizationId:string,correlationId:string,decision:"ALLOW"|"DENY"|"OBSERVED",reason:string)=>ledger!.$executeRawUnsafe(`INSERT INTO control.backfill_audit_ledger (id,operation_id,attempt,phase,organization_id,correlation_id,manifest_digest,decision,reason_code) VALUES ($1::uuid,$2::uuid,$3,$4,$5,$6,$7,$8,$9)`,randomUUID(),operationId,attempt,phase,organizationId,correlationId,digest,decision,reason);
    const assign=(operationId:string,table:"members"|"kpis",recordId:string,organizationId:string)=>assignment!.$executeRawUnsafe(`INSERT INTO control.nullable_root_backfill_assignments (id,operation_id,root_table,record_id,organization_id,manifest_digest) VALUES ($1::uuid,$2::uuid,$3,$4,$5,$6)`,randomUUID(),operationId,table,recordId,organizationId,digest);
    const applyMember=async(client:PrismaClient,id:string)=>{const rows=await client.$queryRawUnsafe<Array<{applied:boolean}>>(`SELECT control.apply_member_backfill_assignment($1) AS applied`,id);return rows[0]?.applied?1:0;};
    const applyKpiGraph=async(client:PrismaClient,id:string)=>{const rows=await client.$queryRawUnsafe<Array<{applied:boolean}>>(`SELECT control.apply_kpi_backfill_assignment($1) AS applied`,id);if(!rows[0]?.applied)throw new Error("ROOT_ADMISSION_DENIED");const children=await reader!.$queryRawUnsafe<Array<{id:string}>>(`SELECT id FROM "kpi_records" WHERE "kpiId"=$1 AND "organizationId" IS NOT NULL`,id);return {root:1,child:children.length};};
    await record("NR01","official migrations deploy clean including nullable-root admission successor",async()=>admin(`SELECT count(*) FROM "_prisma_migrations" WHERE migration_name='20260823100000_w02_dashboard_nullable_root_admission'`,database)==="1");
    await record("NR02","all audit principals are NOSUPERUSER and NOBYPASSRLS",async()=>admin(`SELECT count(*) FROM pg_roles WHERE rolname IN ('${migrator}','${securityOwner}','${assignmentWriter}','${ledgerWriter}','${readerRole}','${tenantA}','${tenantB}') AND (rolsuper OR rolbypassrls)`,database)==="0");
    await record("NR03","assignment and ledger authorities cannot read or mutate tenant roots",async()=>{const [ar,aw,lr,lw]=await Promise.all([denied(()=>assignment!.$queryRawUnsafe('SELECT * FROM "members"')),denied(()=>assignment!.$executeRawUnsafe(`UPDATE "members" SET "organizationId"='${orgA}'`)),denied(()=>ledger!.$queryRawUnsafe('SELECT * FROM "kpis"')),denied(()=>ledger!.$executeRawUnsafe(`UPDATE "kpis" SET "organizationId"='${orgA}'`))]);return ar&&aw&&lr&&lw;});
    await record("NR04","tenant roles cannot forge assignment or ledger rows",async()=>{const [aa,al,ba,bl]=await Promise.all([denied(()=>a!.$executeRawUnsafe('INSERT INTO control.nullable_root_backfill_assignments DEFAULT VALUES')),denied(()=>a!.$executeRawUnsafe('INSERT INTO control.backfill_audit_ledger DEFAULT VALUES')),denied(()=>b!.$executeRawUnsafe('INSERT INTO control.nullable_root_backfill_assignments DEFAULT VALUES')),denied(()=>b!.$executeRawUnsafe('INSERT INTO control.backfill_audit_ledger DEFAULT VALUES'))]);return aa&&al&&ba&&bl;});
    await record("NR05","tenant-bound clients observe distinct session_user principals",async()=>{const [ra,rb]=await Promise.all([a!.$queryRawUnsafe<Array<{session_user:string}>>('SELECT session_user'),b!.$queryRawUnsafe<Array<{session_user:string}>>('SELECT session_user')]);return ra[0]?.session_user===tenantA&&rb[0]?.session_user===tenantB;});
    await record("NR06","explicit manifest assignments are required and no membership/default-owner inference exists",async()=>{const before=await applyMember(a!,"member-a",orgA);await assign(operationA,"members","member-a",orgA);const after=await applyMember(a!,"member-a",orgA);return before===0&&after===1;});
    await record("NR07","A cannot claim B member through foreign ID or foreign owner",async()=>{await assign(operationB,"members","member-b",orgB);const [wrongId,wrongOwner,validB]=await Promise.all([applyMember(a!,"member-b",orgA),applyMember(a!,"member-b",orgB),applyMember(b!,"member-b",orgB)]);return wrongId===0&&wrongOwner===0&&validB===1;});
    await record("NR08","KPI root and KPIRecord child apply only through matching assigned parent graph",async()=>{await assign(operationA,"kpis","kpi-a",orgA);await assign(operationB,"kpis","kpi-b",orgB);const cross=await denied(()=>applyKpiGraph(a!,"kpi-b",orgB));const [ownA,ownB]=await Promise.all([applyKpiGraph(a!,"kpi-a",orgA),applyKpiGraph(b!,"kpi-b",orgB)]);const rows=await reader!.$queryRawUnsafe<Array<{id:string;organization_id:string}>>('SELECT id,"organizationId" AS organization_id FROM "kpi_records" ORDER BY id');return cross&&ownA.root===1&&ownA.child===1&&ownB.root===1&&ownB.child===1&&rows[0]?.organization_id===orgA&&rows[1]?.organization_id===orgB;});
    await record("NR09","parallel A/B tenant-bound applies preserve separate owners",async()=>{const userC="cccccccc-cccc-4ccc-8ccc-cccccccccccc",userD="dddddddd-dddd-4ddd-8ddd-dddddddddddd";admin(`INSERT INTO "users" ("id","name","email","role","isActive","authVersion","createdAt","updatedAt") VALUES ('${userC}','C','c-${suffix}@audit.invalid','MEMBER',true,1,now(),now()),('${userD}','D','d-${suffix}@audit.invalid','MEMBER',true,1,now(),now()); INSERT INTO "members" ("id","userId","status","createdAt","updatedAt") VALUES ('member-c','${userC}','ACTIVE',now(),now()),('member-d','${userD}','ACTIVE',now(),now());`,database);await assign(operationA,"members","member-c",orgA);await assign(operationB,"members","member-d",orgB);const [ca,db]=await Promise.all([applyMember(a!,"member-c",orgA),applyMember(b!,"member-d",orgB)]);return ca===1&&db===1;});
    await record("NR10","Raw GUC and SET ROLE cannot alter admission identity",async()=>{const setRole=await denied(()=>a!.$executeRawUnsafe(`SET ROLE ${tenantB}`));await a!.$executeRawUnsafe("SET application_name='forged-org-b'");const result=await applyMember(a!,"member-b",orgA);return setRole&&result===0;});
    await record("NR11","failed tenant transaction records FAILED without false success and does not corrupt other tenant",async()=>{const op=randomUUID(),corr=randomUUID();admin(`INSERT INTO "kpis" ("id","title","targetEntity","unit","targetValue","status","createdAt","updatedAt") VALUES ('kpi-fail-b','KPI Failure','PROJECT','% ',100,'ACTIVE',now(),now()); INSERT INTO "kpi_records" ("id","kpiId","period","actualValue","targetValue","percent","createdAt","updatedAt") VALUES ('record-fail-b','kpi-fail-b','2026-02',0,100,0,now(),now());`,database);await assign(op,"kpis","kpi-fail-b",orgB);await ledgerEvent(op,1,"STARTED",orgB,corr,"OBSERVED","BEGIN");admin(`CREATE FUNCTION public.fail_dashboard_backfill() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'forced'; END $$; CREATE TRIGGER fail_dashboard_backfill BEFORE UPDATE ON "kpi_records" FOR EACH ROW WHEN (NEW."organizationId" IS NOT NULL) EXECUTE FUNCTION public.fail_dashboard_backfill();`,database);const failed=await denied(()=>applyKpiGraph(b!,"kpi-fail-b",orgB));admin('DROP TRIGGER fail_dashboard_backfill ON "kpi_records"; DROP FUNCTION public.fail_dashboard_backfill();',database);await ledgerEvent(op,1,"FAILED",orgB,corr,"DENY","TX_FAILED");const phases=await reader!.$queryRawUnsafe<Array<{phase:string}>>(`SELECT phase FROM control.backfill_audit_ledger WHERE operation_id=$1::uuid`,op);const unaffected=await reader!.$queryRawUnsafe<Array<{id:string}>>("SELECT id FROM \"members\" WHERE id='member-c' AND \"organizationId\"=$1",orgA);return failed&&phases.some(x=>x.phase==='FAILED')&&!phases.some(x=>x.phase==='SUCCEEDED')&&unaffected.length===1;});
    await record("NR12","retry/resume is idempotent after a visible failure",async()=>{const op=randomUUID(),corr=randomUUID();await ledgerEvent(op,1,"STARTED",orgB,corr,"OBSERVED","RETRY_BEGIN");const result=await applyKpiGraph(b!,"kpi-b",orgB).catch(()=>({root:0,child:0}));await ledgerEvent(op,1,"SUCCEEDED",orgB,corr,"ALLOW","RETRY_APPLIED");const repeat=await applyKpiGraph(b!,"kpi-b",orgB).catch(()=>({root:0,child:0}));return result.root===0&&result.child===0&&repeat.root===0&&repeat.child===0;});
    await record("NR13","missing assignment refuses write and leaves nullable root unchanged",async()=>{const userE="eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee";admin(`INSERT INTO "users" ("id","name","email","role","isActive","authVersion","createdAt","updatedAt") VALUES ('${userE}','E','e-${suffix}@audit.invalid','MEMBER',true,1,now(),now()); INSERT INTO "members" ("id","userId","status","createdAt","updatedAt") VALUES ('member-e','${userE}','ACTIVE',now(),now());`,database);const applied=await applyMember(a!,"member-e",orgA);const rows=await reader!.$queryRawUnsafe<Array<{id:string}>>("SELECT id FROM \"members\" WHERE id='member-e' AND \"organizationId\" IS NULL");return applied===0&&rows.length===1;});
    await record("NR14","ledger duplicate outcome for one operation/attempt is rejected",async()=>{const op=randomUUID(),corr=randomUUID();await ledgerEvent(op,1,"STARTED",orgA,corr,"OBSERVED","BEGIN");await ledgerEvent(op,1,"SUCCEEDED",orgA,corr,"ALLOW","APPLIED");return denied(()=>ledgerEvent(op,1,"SUCCEEDED",orgA,corr,"ALLOW","REPLAY"));});
    await record("NR15","source and audit roles contain no bypass/global credential/Raw GUC identity and proof cleanup is fail-closed",async()=>admin(`SELECT count(*) FROM pg_roles WHERE rolname IN ('${migrator}','${securityOwner}','${assignmentWriter}','${ledgerWriter}','${readerRole}','${tenantA}','${tenantB}') AND (rolsuper OR rolbypassrls)`,database)==="0");
    await Promise.all([a.$disconnect(),b.$disconnect(),assignment.$disconnect(),ledger.$disconnect(),reader.$disconnect()]);a=b=assignment=ledger=reader=undefined;const finalCleanup=cleanup();for(const row of evidence)row.cleanupStatus=finalCleanup.ok?"PASS":"FAIL";const payload:Record<string,unknown>={status:"PENDING",startedAt,finishedAt:new Date().toISOString(),environment:"disposable-postgresql-audit",mandatoryIds:ids,evidence,diagnostics,hardFailures:[],cleanup:finalCleanup,hygiene:{status:"PENDING"},credentialsPersisted:false,productionResourcesTouched:false,rawGucIdentityUsed:false,globalTenantCredentialUsed:false,ownerOrBypassUsedForTenantEvidence:false};write(payload);const hygiene=run("node",["scripts/w02-audit-artifact-hygiene-scan.mjs"]);payload.hygiene={status:hygiene.status===0?"PASS_AUDIT_ARTIFACT_HYGIENE_SCAN":"FAIL_AUDIT_ARTIFACT_HYGIENE_SCAN"};const failed=evidence.filter(row=>row.result!=="PASS").map(row=>row.id);payload.hardFailures=failed;payload.status=finalCleanup.ok&&hygiene.status===0&&failed.length===0?"PASS_DASHBOARD_NULLABLE_ROOT_CLEAN":"FAIL";write(payload);process.stdout.write(`${JSON.stringify({status:payload.status,evidenceFile,hardFailures:failed,cleanup:finalCleanup,hygiene:payload.hygiene},null,2)}\n`);process.exitCode=payload.status==="PASS_DASHBOARD_NULLABLE_ROOT_CLEAN"?0:2;
  } catch { await Promise.all([a?.$disconnect(),b?.$disconnect(),assignment?.$disconnect(),ledger?.$disconnect(),reader?.$disconnect()].map(item=>item?.catch(()=>undefined)));const finalCleanup=cleanup();write({status:finalCleanup.ok?"FAIL_SETUP_OR_HARNESS":"FAIL_CLEANUP",startedAt,finishedAt:new Date().toISOString(),environment:"disposable-postgresql-audit",mandatoryIds:ids,error:"REDACTED_HARNESS_ERROR",cleanup:finalCleanup,hygiene:{status:"NOT_RUN"},credentialsPersisted:false,productionResourcesTouched:false,rawGucIdentityUsed:false,globalTenantCredentialUsed:false,ownerOrBypassUsedForTenantEvidence:false});process.stderr.write(`Dashboard nullable-root clean proof failed; redacted evidence: ${evidenceFile}\n`);process.exitCode=2; }
}
void main();
