import { randomBytes } from "node:crypto";
import { chmodSync, readFileSync, writeFileSync } from "node:fs";
import { spawnSync } from "node:child_process";
import { PrismaClient } from "@prisma/client";
import { BrokerDeniedError, TenantAccessBroker } from "../src/lib/tenant-access-broker";
import { TenantBoundPrismaCredentialAuthority, TenantBoundPrismaExecutor, type TenantConnectionProvider } from "../src/lib/tenant-bound-prisma-authority";
import { BudgetExpenseRepository, BudgetExpenseScopeError } from "../src/lib/budget-expense-repository";
import type { TenantContext } from "../src/lib/tenant-context";

const suffix = `${Date.now()}_${process.pid}`; const database = `asas_rls_budget_audit_${suffix}`; const migrator = `rls_budget_migrator_${suffix}`; const control = `rls_budget_control_${suffix}`; const a1 = `rls_budget_a1_${suffix}`; const a2 = `rls_budget_a2_${suffix}`; const b1 = `rls_budget_b1_${suffix}`; const none = `rls_budget_none_${suffix}`; const evidenceFile = `/tmp/w02-rls-wave3-budget-evidence-${suffix}.json`;
const mandatoryIds = ["BE-R01", "BE-R02", "BE-R03", "BE-R04", "BE-R05", "BE-R06", "BE-R07", "BE-R08", "BE-R09", "BE-R10", "BE-R11", "BE-R12"];
const password = () => randomBytes(30).toString("base64url"); const passwords = { migrator: password(), control: password(), a1: password(), a2: password(), b1: password(), none: password() };
const orgA = "11111111-1111-4111-8111-111111111111"; const orgB = "22222222-2222-4222-8222-222222222222"; const userA = "aaaaaaaa-0000-4000-8000-000000000001"; const userB = "bbbbbbbb-0000-4000-8000-000000000002"; const membershipA = "aaaaaaaa-0000-4000-8000-000000000101"; const membershipB = "bbbbbbbb-0000-4000-8000-000000000102"; const evidence: Array<Record<string, unknown>> = [];
function run(command: string, args: string[], options: Record<string, unknown> = {}) { return spawnSync(command, args, { encoding: "utf8", ...options }); }
function sql(statement: string, db = "postgres") { const result = run("sudo", ["-u", "postgres", "psql", "-d", db, "-X", "-v", "ON_ERROR_STOP=1", "-At"], { input: statement }); if (result.status !== 0) throw new Error("AUDIT_ADMIN_SQL_FAILED"); return result.stdout.trim(); }
function url(role: string, value: string) { return `postgresql://${role}:${value}@127.0.0.1:5432/${database}?schema=public`; }
function write(payload: Record<string, unknown>) { writeFileSync(evidenceFile, `${JSON.stringify(payload, null, 2)}\n`, { mode: 0o600 }); chmodSync(evidenceFile, 0o600); }
function context(organizationId: string, userId: string, membershipId: string, correlationId: string, sessionVersion = 1): TenantContext { return Object.freeze({ organizationId, userId, membershipId, correlationId, sessionVersion, policySnapshotVersion: 1 }); }
async function record(id: string, expected: string, action: () => Promise<boolean>) { try { const actual = await action(); evidence.push({ id, expected, actual, result: actual ? "PASS" : "FAIL", environment: "disposable-postgresql-audit", cleanupStatus: "PENDING" }); } catch { evidence.push({ id, expected, actual: "REDACTED_EXCEPTION", result: "FAIL", environment: "disposable-postgresql-audit", cleanupStatus: "PENDING" }); } }
async function denied(action: () => Promise<unknown>) { try { await action(); return false; } catch { return true; } }
async function deniedBroker(action: () => Promise<unknown>, code: string) { try { await action(); return false; } catch (error) { return error instanceof BrokerDeniedError && error.code === code; } }
function cleanup() { const roles = [migrator, control, a1, a2, b1, none]; const errors: string[] = []; try { sql(`SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname='${database}' AND pid <> pg_backend_pid();`); } catch { errors.push("TERMINATE_FAILED"); } try { sql(`DROP DATABASE IF EXISTS ${database} WITH (FORCE);`); } catch { errors.push("DROP_DATABASE_FAILED"); } for (const role of roles) try { sql(`DROP ROLE IF EXISTS ${role};`); } catch { errors.push("DROP_ROLE_FAILED"); } let residue = ""; try { residue = sql(`SELECT datname FROM pg_database WHERE datname='${database}' UNION ALL SELECT rolname FROM pg_roles WHERE rolname IN (${roles.map((role) => `'${role}'`).join(",")});`); } catch { errors.push("RESIDUE_SCAN_FAILED"); } return { ok: errors.length === 0 && residue === "", errors, residueCount: residue ? residue.split("\n").filter(Boolean).length : 0 }; }

async function main() {
  let controlDb: PrismaClient | null = null; let directA: PrismaClient | null = null; let directB: PrismaClient | null = null; let directNone: PrismaClient | null = null; const startedAt = new Date().toISOString(); let phase = "bootstrap-roles";
  try {
    sql(`CREATE ROLE ${migrator} LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS PASSWORD '${passwords.migrator}'; CREATE DATABASE ${database} OWNER ${migrator}; CREATE ROLE ${control} LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS PASSWORD '${passwords.control}'; CREATE ROLE ${a1} LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS PASSWORD '${passwords.a1}'; CREATE ROLE ${a2} LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS PASSWORD '${passwords.a2}'; CREATE ROLE ${b1} LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS PASSWORD '${passwords.b1}'; CREATE ROLE ${none} LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS PASSWORD '${passwords.none}';`);
    phase = "migration-deploy"; if (run("./node_modules/.bin/prisma", ["migrate", "deploy", "--schema", "prisma/schema.prisma"], { env: { ...process.env, DATABASE_URL: url(migrator, passwords.migrator) } }).status !== 0) throw new Error("MIGRATION_DEPLOY_FAILED");
    const tenantRoles = `${a1}, ${a2}, ${b1}, ${none}`;
    phase = "grants-and-seed"; sql(`GRANT CONNECT ON DATABASE ${database} TO ${control}, ${tenantRoles}; GRANT USAGE ON SCHEMA public, security TO ${control}, ${tenantRoles}; GRANT EXECUTE ON FUNCTION security.current_session_organization_id() TO ${tenantRoles}; GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "organizations", "users", "organization_memberships", "tenant_database_principals", "tenant_access_leases", "tenant_broker_audit_events" TO ${control}; GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "budgets", "budget_items", "expenses", "audit_logs" TO ${tenantRoles};`, database);
    phase = "seed-organizations"; sql(`INSERT INTO "organizations" ("id","name","createdAt","updatedAt") VALUES ('${orgA}','Organization A',now(),now()),('${orgB}','Organization B',now(),now());`, database);
    phase = "seed-users"; sql(`INSERT INTO "users" ("id","name","email","role","isActive","authVersion","activeOrganizationId","createdAt","updatedAt") VALUES ('${userA}','A','a-${suffix}@audit.invalid','MEMBER',true,1,'${orgA}',now(),now()),('${userB}','B','b-${suffix}@audit.invalid','MEMBER',true,1,'${orgB}',now(),now());`, database);
    phase = "seed-memberships"; sql(`INSERT INTO "organization_memberships" ("id","organizationId","userId","role","isActive","policyVersion","createdAt","updatedAt") VALUES ('${membershipA}','${orgA}','${userA}','MEMBER',true,1,now(),now()),('${membershipB}','${orgB}','${userB}','MEMBER',true,1,now(),now());`, database);
    phase = "seed-role-mapping"; sql(`INSERT INTO security.role_to_organization (role_oid, organization_id) VALUES ('${a1}'::regrole::oid,'${orgA}'),('${b1}'::regrole::oid,'${orgB}');`, database);
    phase = "seed-principals"; sql(`INSERT INTO "tenant_database_principals" ("id","organizationId","principalName","credentialReference","generation","status","activatedAt","createdAt","updatedAt") VALUES ('principal-a1','${orgA}','${a1}','audit://budget-rls/a1',1,'ACTIVE',now(),now(),now()),('principal-b1','${orgB}','${b1}','audit://budget-rls/b1',1,'ACTIVE',now(),now(),now());`, database);
    phase = "seed-financial-fixtures"; sql(`INSERT INTO "budgets" ("id","organizationId","title","fiscalYear","totalAmount","status","createdAt","updatedAt") VALUES ('budget-a','${orgA}','A','2026',100,'ACTIVE',now(),now()),('budget-b','${orgB}','B','2026',200,'ACTIVE',now(),now()),('budget-null',NULL,'N','2026',1,'DRAFT',now(),now()); INSERT INTO "budget_items" ("id","organizationId","budgetId","category","allocated") VALUES ('item-a','${orgA}','budget-a','A',50),('item-b','${orgB}','budget-b','B',50); INSERT INTO "expenses" ("id","organizationId","title","amount","status","expenseDate","budgetItemId") VALUES ('expense-a','${orgA}','A',5,'PENDING',now(),'item-a'),('expense-b','${orgB}','B',6,'PENDING',now(),'item-b');`, database);
    phase = "runtime-proof";
    controlDb = new PrismaClient({ datasources: { db: { url: url(control, passwords.control) } } }); directA = new PrismaClient({ datasources: { db: { url: url(a1, passwords.a1) } } }); directB = new PrismaClient({ datasources: { db: { url: url(b1, passwords.b1) } } }); directNone = new PrismaClient({ datasources: { db: { url: url(none, passwords.none) } } });
    const entries = new Map([["audit://budget-rls/a1", { principalName: a1, value: url(a1, passwords.a1) }], ["audit://budget-rls/a2", { principalName: a2, value: url(a2, passwords.a2) }], ["audit://budget-rls/b1", { principalName: b1, value: url(b1, passwords.b1) }]]); const unavailable = new Set<string>(); let checkoutCount = 0; let discardCount = 0;
    const provider: TenantConnectionProvider = { async checkout(input) { const entry = entries.get(input.credentialReference); if (!entry || unavailable.has(input.credentialReference) || entry.principalName !== input.principalName) throw new Error("PROVIDER_UNAVAILABLE"); const prisma = new PrismaClient({ datasources: { db: { url: entry.value } } }); const rows = await prisma.$queryRawUnsafe<Array<{ session_user: string }>>("SELECT session_user"); if (rows[0]?.session_user !== input.principalName) { await prisma.$disconnect(); throw new Error("SESSION_USER_MISMATCH"); } checkoutCount += 1; return { prisma, discard: async () => { discardCount += 1; await prisma.$disconnect(); } }; } };
    const authority = new TenantBoundPrismaCredentialAuthority(provider); const executor = new TenantBoundPrismaExecutor(new TenantAccessBroker(controlDb, authority, 5_000)); const repo = new BudgetExpenseRepository(executor); const ctxA = context(orgA, userA, membershipA, "budget-rls-a"); const ctxB = context(orgB, userB, membershipB, "budget-rls-b"); const identity = (db: PrismaClient) => db.$queryRawUnsafe<Array<{ session_user: string }>>("SELECT session_user").then((rows) => rows[0]?.session_user);
    await record("BE-R01", "official migration enables FORCE RLS and three budget family policies with no bypass tenant role", async () => sql("SELECT count(*) FROM _prisma_migrations WHERE migration_name='20260824093000_w02_rls_wave3_budget_expense' AND finished_at IS NOT NULL", database) === "1" && sql("SELECT count(*) FROM pg_class WHERE relname IN ('budgets','budget_items','expenses') AND relrowsecurity AND relforcerowsecurity", database) === "3" && sql(`SELECT count(*) FROM pg_roles WHERE rolname IN ('${a1}','${a2}','${b1}','${none}') AND (rolsuper OR rolbypassrls)`, database) === "0");
    await record("BE-R02", "A/B direct root reads and writes remain isolated", async () => (await directA!.budget.count()) === 1 && (await directB!.expense.count()) === 1 && (await directA!.budget.findUnique({ where: { id: "budget-b" } })) === null && await denied(() => directA!.budget.create({ data: { organizationId: orgB, title: "Denied", fiscalYear: "2026", totalAmount: 1 } })));
    await record("BE-R03", "unmapped login and nullable roots fail closed", async () => (await directNone!.budget.count()) === 0 && (await directA!.budget.findUnique({ where: { id: "budget-null" } })) === null && await denied(() => directA!.budget.create({ data: { organizationId: null, title: "Denied", fiscalYear: "2026", totalAmount: 1 } })));
    await record("BE-R04", "foreign parent budget item and expense writes are denied by RLS", async () => await denied(() => directA!.budgetItem.create({ data: { organizationId: orgA, budgetId: "budget-b", category: "Denied", allocated: 1 } })) && await denied(() => directA!.expense.create({ data: { organizationId: orgA, budgetItemId: "item-b", title: "Denied", amount: 1 } })));
    await record("BE-R05", "Broker executor verifies session_user and RLS rows A/B", async () => { const [a, b] = await Promise.all([executor.execute(ctxA, async (db) => ({ user: await identity(db), rows: await db.budget.count() })), executor.execute(ctxB, async (db) => ({ user: await identity(db), rows: await db.budget.count() }))]); return a.user === a1 && b.user === b1 && a.rows === 1 && b.rows === 1 && discardCount >= checkoutCount; });
    await record("BE-R06", "BudgetExpenseRepository rejects foreign parent and retains scoped read", async () => { const read = await repo.getBudgetById(ctxA, "budget-b"); try { await repo.addBudgetItem(ctxA, { budgetId: "budget-b", category: "Denied", allocated: 1 }); return read === null && false; } catch (error) { return read === null && error instanceof BudgetExpenseScopeError && error.code === "FORBIDDEN_RELATION"; } });
    await record("BE-R07", "repository context stamps ownership for new budget/item/expense", async () => { const budget = await repo.createBudget(ctxA, { title: "Context", fiscalYear: "2027", totalAmount: 20 }); const item = await repo.addBudgetItem(ctxA, { budgetId: budget.id, category: "Context", allocated: 20 }); const expense = await repo.createExpense(ctxA, { budgetItemId: item.id, title: "Context", amount: 2 }); return budget.organizationId === orgA && item.organizationId === orgA && expense.organizationId === orgA; });
    await record("BE-R08", "SET ROLE cannot switch A session_user to B", async () => await denied(() => directA!.$executeRawUnsafe(`SET ROLE ${b1}`)) && await identity(directA!) === a1);
    await record("BE-R09", "lease replay, inactive membership and stale session fail before data access", async () => { const lifecycle = new TenantAccessBroker(controlDb!, authority, 5_000); const lease = await lifecycle.issueLease(ctxA); await lifecycle.execute(ctxA, lease, async ({ prisma }) => identity(prisma!)); const replay = await deniedBroker(() => lifecycle.execute(ctxA, lease, async () => "unexpected"), "LEASE_REPLAY"); await controlDb!.organizationMembership.update({ where: { id: membershipB }, data: { isActive: false } }); const revoked = await deniedBroker(() => executor.execute(ctxB, identity), "MEMBERSHIP_ORGANIZATION_MISMATCH"); const stale = await deniedBroker(() => executor.execute(context(orgA, userA, membershipA, "budget-stale", 0), identity), "STALE_SESSION"); return replay && revoked && stale; });
    await record("BE-R10", "provider outage and principal rotation fail closed then move only to A2", async () => { unavailable.add("audit://budget-rls/a1"); const outage = await deniedBroker(() => repo.listBudgets(ctxA), "AUTHORITY_OR_OPERATION_FAILURE"); unavailable.delete("audit://budget-rls/a1"); await controlDb!.tenantDatabasePrincipal.update({ where: { id: "principal-a1" }, data: { status: "REVOKED", revokedAt: new Date() } }); sql(`UPDATE security.role_to_organization SET revoked_at=now() WHERE role_oid='${a1}'::regrole::oid AND revoked_at IS NULL; INSERT INTO security.role_to_organization (role_oid, organization_id) VALUES ('${a2}'::regrole::oid,'${orgA}');`, database); await controlDb!.tenantDatabasePrincipal.create({ data: { id: "principal-a2", organizationId: orgA, principalName: a2, credentialReference: "audit://budget-rls/a2", generation: 2, status: "ACTIVE", activatedAt: new Date() } }); return outage && await executor.execute(ctxA, identity) === a2; });
    await record("BE-R11", "parallel operations and source guard show no global Prisma or raw identity fallback", async () => { const [a, b] = await Promise.all([repo.listBudgets(ctxA), repo.listBudgets(ctxB).catch(() => [])]); const source = readFileSync("src/lib/budget-expense-repository.ts", "utf8"); return a.length >= 1 && b.length === 0 && checkoutCount >= 4 && discardCount >= checkoutCount && !/(from "@\/lib\/db"|current_setting|set_config|DATABASE_URL)/.test(source); });
    await record("BE-R12", "mandatory IDs are unique and all prior gates recorded", async () => { const observed = evidence.map((item) => item.id); return new Set(mandatoryIds).size === mandatoryIds.length && mandatoryIds.slice(0, 11).every((id) => observed.includes(id)) && new Set(observed).size === observed.length; });
    await Promise.all([controlDb.$disconnect(), directA.$disconnect(), directB.$disconnect(), directNone.$disconnect()]); controlDb = null; directA = null; directB = null; directNone = null; const finalCleanup = cleanup(); for (const item of evidence) item.cleanupStatus = finalCleanup.ok ? "PASS" : "FAIL"; const hygiene = run("node", ["scripts/w02-audit-artifact-hygiene-scan.mjs"]).status === 0; const failed = evidence.filter((item) => item.result !== "PASS").map((item) => item.id); const payload: Record<string, unknown> = { status: finalCleanup.ok && hygiene && failed.length === 0 && evidence.length === mandatoryIds.length ? "PASS_RLS_WAVE3_BUDGET_EXPENSE_RUNTIME" : finalCleanup.ok ? "FAIL" : "FAIL_CLEANUP", startedAt, finishedAt: new Date().toISOString(), environment: "disposable-postgresql-audit", databaseAlias: database, mandatoryIds, evidence, hardFailures: failed, cleanup: finalCleanup, hygiene: { status: hygiene ? "PASS" : "FAIL" }, credentialsPersisted: false, productionResourcesTouched: false, rawGucIdentityUsed: false, globalPrismaFallback: false, ownerOrBypassUsedForTenantEvidence: false }; write(payload); process.stdout.write(`${JSON.stringify({ status: payload.status, evidenceFile, hardFailures: failed, cleanup: finalCleanup }, null, 2)}\n`); process.exitCode = payload.status === "PASS_RLS_WAVE3_BUDGET_EXPENSE_RUNTIME" ? 0 : 2;
  } catch { await Promise.all([controlDb?.$disconnect().catch(() => undefined), directA?.$disconnect().catch(() => undefined), directB?.$disconnect().catch(() => undefined), directNone?.$disconnect().catch(() => undefined)]); const finalCleanup = cleanup(); write({ status: finalCleanup.ok ? "FAIL_SETUP_OR_HARNESS" : "FAIL_CLEANUP", startedAt, finishedAt: new Date().toISOString(), environment: "disposable-postgresql-audit", databaseAlias: database, phase, mandatoryIds, cleanup: finalCleanup, credentialsPersisted: false, productionResourcesTouched: false, rawGucIdentityUsed: false }); process.exitCode = 2; }
}
void main();
