import { chmodSync, readFileSync, writeFileSync } from "node:fs";
import { spawnSync } from "node:child_process";
import { randomBytes } from "node:crypto";
import { PrismaClient } from "@prisma/client";
import { BrokerDeniedError, TenantAccessBroker } from "../src/lib/tenant-access-broker";
import { TenantBoundPrismaCredentialAuthority, TenantBoundPrismaExecutor, type TenantConnectionProvider } from "../src/lib/tenant-bound-prisma-authority";
import { MemberKpiRepository, MemberKpiScopeError } from "../src/lib/member-kpi-repository";
import type { TenantContext } from "../src/lib/tenant-context";

/** W02 Member/KPI proof: disposable PostgreSQL only; no RLS policy or production provider. */
const suffix = `${Date.now()}_${process.pid}`;
const database = `asas_member_kpi_audit_${suffix}`;
const roles = ["migrator", "control", "a1", "a2", "b1"].map((item) => `mk_${item}_${suffix}`);
const [migrator, controlRole, tenantA1, tenantA2, tenantB1] = roles;
const passwords = Object.fromEntries(roles.map((role) => [role, randomBytes(30).toString("base64url")])) as Record<string, string>;
const evidenceFile = `/tmp/w02-member-kpi-evidence-${suffix}.json`;
const mandatoryIds = ["MK01", "MK02", "MK03", "MK04", "MK05", "MK06", "MK07", "MK08", "MK09", "MK10"];
const evidence: Array<Record<string, unknown>> = [];
const orgA = "11111111-1111-4111-8111-111111111111", orgB = "22222222-2222-4222-8222-222222222222";
const userA = "aaaaaaaa-0000-4000-8000-000000000001", userB = "bbbbbbbb-0000-4000-8000-000000000002", userC = "cccccccc-0000-4000-8000-000000000003";
const membershipA = "aaaaaaaa-0000-4000-8000-000000000101", membershipB = "bbbbbbbb-0000-4000-8000-000000000102";
const run = (command: string, args: string[], options: Record<string, unknown> = {}) => spawnSync(command, args, { encoding: "utf8", ...options });
function adminSql(sql: string, db = "postgres") { const result = run("sudo", ["-u", "postgres", "psql", "-d", db, "-X", "-v", "ON_ERROR_STOP=1", "-At"], { input: sql }); if (result.status !== 0) throw new Error("AUDIT_ADMIN_SQL_FAILED"); return result.stdout.trim(); }
function url(role: string) { return `postgresql://${role}:${passwords[role]}@127.0.0.1:5432/${database}?schema=public`; }
function ctx(organizationId: string, userId: string, membershipId: string, correlationId: string, sessionVersion = 1, policySnapshotVersion = 1): TenantContext { return Object.freeze({ organizationId, userId, membershipId, correlationId, sessionVersion, policySnapshotVersion }); }
function writeEvidence(payload: Record<string, unknown>) { writeFileSync(evidenceFile, `${JSON.stringify(payload, null, 2)}\n`, { mode: 0o600 }); chmodSync(evidenceFile, 0o600); }
async function record(id: string, expected: string, action: () => Promise<boolean>) { try { const actual = await action(); evidence.push({ id, expected, actual, result: actual ? "PASS" : "FAIL", timestamp: new Date().toISOString(), environment: "disposable-postgresql-audit", cleanupStatus: "PENDING" }); } catch (error) { const actual = error instanceof Error && /^MK08_/.test(error.message) ? error.message : "REDACTED_EXCEPTION"; evidence.push({ id, expected, actual, result: "FAIL", timestamp: new Date().toISOString(), environment: "disposable-postgresql-audit", cleanupStatus: "PENDING" }); } }
async function denies(action: () => Promise<unknown>, code?: string) { try { await action(); return false; } catch (error) { const errorCode = typeof error === "object" && error && "code" in error ? (error as { code?: unknown }).code : undefined; return code ? errorCode === code : error instanceof MemberKpiScopeError; } }
async function denialCode(action: () => Promise<unknown>) { try { await action(); return "NO_DENIAL"; } catch (error) { if (typeof error === "object" && error && "code" in error && typeof (error as { code?: unknown }).code === "string") return (error as { code: string }).code; const name = error instanceof Error ? error.name : "UNKNOWN"; return `REDACTED_${name}`; } }
function cleanup() { const errors: string[] = []; try { adminSql(`SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname='${database}' AND pid<>pg_backend_pid();`); } catch { errors.push("TERMINATE_FAILED"); } try { adminSql(`DROP DATABASE IF EXISTS ${database};`); } catch { errors.push("DROP_DATABASE_FAILED"); } for (const role of roles) try { adminSql(`DROP ROLE IF EXISTS ${role};`); } catch { errors.push("DROP_ROLE_FAILED"); } let residue = ""; try { residue = adminSql(`SELECT datname FROM pg_database WHERE datname='${database}' UNION ALL SELECT rolname FROM pg_roles WHERE rolname IN (${roles.map((role) => `'${role}'`).join(",")});`); } catch { errors.push("RESIDUE_SCAN_FAILED"); } return { ok: errors.length === 0 && residue === "", errors, residueCount: residue ? residue.split("\n").filter(Boolean).length : 0 }; }

async function main() {
  let controlPrisma: PrismaClient | null = null;
  const startedAt = new Date().toISOString();
  try {
    adminSql(`CREATE ROLE ${migrator} LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS PASSWORD '${passwords[migrator]}'; CREATE DATABASE ${database} OWNER ${migrator}; CREATE ROLE ${controlRole} LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS PASSWORD '${passwords[controlRole]}'; CREATE ROLE ${tenantA1} LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS PASSWORD '${passwords[tenantA1]}'; CREATE ROLE ${tenantA2} LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS PASSWORD '${passwords[tenantA2]}'; CREATE ROLE ${tenantB1} LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS PASSWORD '${passwords[tenantB1]}';`);
    if (run("./node_modules/.bin/prisma", ["migrate", "deploy", "--schema", "prisma/schema.prisma"], { env: { ...process.env, DATABASE_URL: url(migrator) } }).status !== 0) throw new Error("MIGRATION_DEPLOY_FAILED");
    adminSql(`GRANT CONNECT ON DATABASE ${database} TO ${roles.slice(1).join(",")}; GRANT USAGE ON SCHEMA public TO ${roles.slice(1).join(",")}; GRANT SELECT,INSERT,UPDATE,DELETE ON TABLE "organizations","users","organization_memberships","tenant_database_principals","tenant_access_leases","tenant_broker_audit_events" TO ${controlRole}; GRANT SELECT ON TABLE "users","organization_memberships" TO ${tenantA1},${tenantA2},${tenantB1}; GRANT SELECT,INSERT,UPDATE,DELETE ON TABLE "members","membership_payments","kpis","kpi_records" TO ${tenantA1},${tenantA2},${tenantB1};`, database);
    adminSql(`INSERT INTO "organizations" ("id","name","createdAt","updatedAt") VALUES ('${orgA}','A',now(),now()),('${orgB}','B',now(),now()); INSERT INTO "users" ("id","name","email","role","isActive","authVersion","activeOrganizationId","createdAt","updatedAt") VALUES ('${userA}','A','a-${suffix}@audit.invalid','MEMBER',true,1,'${orgA}',now(),now()),('${userB}','B','b-${suffix}@audit.invalid','MEMBER',true,1,'${orgB}',now(),now()),('${userC}','C','c-${suffix}@audit.invalid','MEMBER',true,1,'${orgA}',now(),now()),('dddddddd-0000-4000-8000-000000000004','Null','null-${suffix}@audit.invalid','MEMBER',true,1,NULL,now(),now()); INSERT INTO "organization_memberships" ("id","organizationId","userId","role","isActive","policyVersion","createdAt","updatedAt") VALUES ('${membershipA}','${orgA}','${userA}','MEMBER',true,1,now(),now()),('${membershipB}','${orgB}','${userB}','MEMBER',true,1,now(),now()),('membership-c','${orgA}','${userC}','MEMBER',true,1,now(),now()); INSERT INTO security.role_to_organization (role_oid,organization_id) VALUES ('${tenantA1}'::regrole::oid,'${orgA}'),('${tenantB1}'::regrole::oid,'${orgB}'); INSERT INTO "tenant_database_principals" ("id","organizationId","principalName","credentialReference","generation","status","activatedAt","createdAt","updatedAt") VALUES ('principal-a1','${orgA}','${tenantA1}','audit://mk/a1',1,'ACTIVE',now(),now(),now()),('principal-b1','${orgB}','${tenantB1}','audit://mk/b1',1,'ACTIVE',now(),now(),now()); INSERT INTO "members" ("id","organizationId","userId","membershipType","status","startDate","membershipFee","paidAmount","paymentStatus","createdAt","updatedAt") VALUES ('member-a','${orgA}','${userA}','REGULAR','ACTIVE',now(),100,0,'PENDING',now(),now()),('member-b','${orgB}','${userB}','REGULAR','ACTIVE',now(),100,0,'PENDING',now(),now()),('member-null',NULL,'dddddddd-0000-4000-8000-000000000004','REGULAR','ACTIVE',now(),0,0,'PENDING',now(),now()); INSERT INTO "kpis" ("id","organizationId","title","targetEntity","unit","targetValue","frequency","status","createdAt","updatedAt") VALUES ('kpi-a','${orgA}','KPI A','DEPARTMENT','COUNT',100,'monthly','ACTIVE',now(),now()),('kpi-b','${orgB}','KPI B','DEPARTMENT','COUNT',100,'monthly','ACTIVE',now(),now()),('kpi-null',NULL,'KPI NULL','DEPARTMENT','COUNT',100,'monthly','ACTIVE',now(),now()); INSERT INTO "kpi_records" ("id","organizationId","kpiId","period","actualValue","targetValue","percent","createdAt","updatedAt") VALUES ('record-a','${orgA}','kpi-a','2026-01',10,100,10,now(),now()),('record-b','${orgB}','kpi-b','2026-01',20,100,20,now(),now()),('record-null',NULL,'kpi-null','2026-01',0,100,0,now(),now());`, database);
    controlPrisma = new PrismaClient({ datasources: { db: { url: url(controlRole) } } });
    const entries = new Map([["audit://mk/a1", { principalName: tenantA1, url: url(tenantA1) }], ["audit://mk/a2", { principalName: tenantA2, url: url(tenantA2) }], ["audit://mk/b1", { principalName: tenantB1, url: url(tenantB1) }]]);
    const unavailable = new Set<string>(); const observations: Array<{ correlationId: string; identity: string; client: PrismaClient }> = []; let checkoutCount = 0, discardCount = 0;
    const provider: TenantConnectionProvider = { async checkout(input) { const entry = entries.get(input.credentialReference); if (!entry || unavailable.has(input.credentialReference) || entry.principalName !== input.principalName) throw new Error("AUTHORITY_MAPPING_OR_PROVIDER_UNAVAILABLE"); const prisma = new PrismaClient({ datasources: { db: { url: entry.url } } }); const rows = await prisma.$queryRawUnsafe<Array<{ session_user: string }>>("SELECT session_user"); if (rows[0]?.session_user !== input.principalName) { await prisma.$disconnect(); throw new Error("SESSION_USER_MISMATCH"); } checkoutCount++; observations.push({ correlationId: input.correlationId, identity: rows[0].session_user, client: prisma }); return { prisma, discard: async () => { discardCount++; await prisma.$disconnect(); } }; } };
    const authority = new TenantBoundPrismaCredentialAuthority(provider), broker = new TenantAccessBroker(controlPrisma, authority, 5_000), executor = new TenantBoundPrismaExecutor(broker), repository = new MemberKpiRepository(executor);
    const ctxA = ctx(orgA, userA, membershipA, "mk-a"), ctxB = ctx(orgB, userB, membershipB, "mk-b");
    await record("MK01", "Broker lease is consumed and provider verifies A session_user", async () => { const before = await controlPrisma!.tenantAccessLease.count({ where: { organizationId: orgA, status: "CONSUMED" } }); const result = await repository.listMembers(ctxA, { skip: 0, take: 10 }); const after = await controlPrisma!.tenantAccessLease.count({ where: { organizationId: orgA, status: "CONSUMED" } }); return result.data.length === 1 && after > before && observations.some((item) => item.correlationId === ctxA.correlationId && item.identity === tenantA1); });
    await record("MK02", "A/B lists and details disclose only their own Member/KPI roots and children", async () => { const [aMembers,bMembers,aKpis,bKpis,aDetail,bDetail] = await Promise.all([repository.listMembers(ctxA,{skip:0,take:10}),repository.listMembers(ctxB,{skip:0,take:10}),repository.listKpis(ctxA),repository.listKpis(ctxB),repository.getMember(ctxA,"member-a"),repository.getMember(ctxB,"member-b")]); return aMembers.data.length===1 && bMembers.data.length===1 && aKpis.length===1 && bKpis.length===1 && aDetail?.organizationId===orgA && bDetail?.organizationId===orgB && aKpis[0]?.records[0]?.organizationId===orgA && bKpis[0]?.records[0]?.organizationId===orgB; });
    await record("MK03", "Foreign Member IDs are hidden and renewal IDOR fails before write", async () => (await repository.getMember(ctxA,"member-b")) === null && await denies(() => repository.renewMember(ctxA,"member-b",{amount:1,receiptNo:"foreign"})));
    await record("MK04", "Member create requires explicit active same-organization membership and ignores forged organization identity", async () => { const created = await repository.createMember(ctxA,{userId:userC,membershipFee:10}); const denied = await denies(() => repository.createMember(ctxA,{userId:userB})); return created.organizationId===orgA && denied; });
    await record("MK05", "Renewal payment inherits the scoped Member ownership and updates only same-tenant member", async () => { const payment = await repository.renewMember(ctxA,"member-a",{amount:100,receiptNo:"a-renew",now:new Date("2026-02-01T00:00:00.000Z")}); const chain = await executor.execute(ctxA,(db) => db.membershipPayment.findFirst({where:{id:payment.id},include:{member:true}})); return chain?.member.organizationId===orgA && chain.member.paymentStatus==="PAID"; });
    await record("MK06", "KPIRecord foreign parent is denied; same-tenant record persists with explicit parent/child ownership", async () => { const denied = await denies(() => repository.addKpiRecord(ctxA,{kpiId:"kpi-b",period:"2026-02",actualValue:1,targetValue:10})); const created = await repository.addKpiRecord(ctxA,{kpiId:"kpi-a",period:"2026-02",actualValue:100,targetValue:100}); return denied && created.organizationId===orgA && created.kpiId==="kpi-a"; });
    await record("MK07", "Nullable legacy roots and children are omitted from tenant lists", async () => { const [members,kpis] = await Promise.all([repository.listMembers(ctxA,{skip:0,take:20}),repository.listKpis(ctxA)]); return !members.data.some((item) => item.id==="member-null" || item.organizationId===null) && !kpis.some((item) => item.id==="kpi-null" || item.organizationId===null || item.records.some((record) => record.organizationId===null)); });
    await record("MK08", "Consumed replay, revoked lease, stale session and stale policy deny before data-plane execution", async () => { const lease = await broker.issueLease(ctxA); await broker.execute(ctxA,lease,async (input) => input.prisma.$queryRawUnsafe("SELECT 1")); const replay = await denies(() => broker.execute(ctxA,lease,async () => "unexpected"),"LEASE_REPLAY"); const revoked = await broker.issueLease(ctxB); await broker.revokeLease(revoked.leaseId,ctxB.correlationId); const revokedDenied = await denies(() => broker.execute(ctxB,revoked,async () => "unexpected"),"LEASE_REVOKED"); const staleSessionCode = await denialCode(() => repository.listMembers(ctx(orgA,userA,membershipA,"mk-stale-session",0),{skip:0,take:10})); const stalePolicyCode = await denialCode(() => repository.listKpis(ctx(orgA,userA,membershipA,"mk-stale-policy",1,0))); const failure = [["REPLAY",replay],["REVOKED",revokedDenied],["STALE_SESSION",staleSessionCode==="STALE_SESSION"],["STALE_POLICY",stalePolicyCode==="STALE_POLICY"]].find(([,value])=>!value); if (failure) throw new Error(`MK08_${failure[0]}_${failure[0]==="STALE_SESSION"?staleSessionCode:failure[0]==="STALE_POLICY"?stalePolicyCode:"DENIAL_FAILED"}_FAILED`); return true; });
    await record("MK09", "Rotation, provider outage and parallel A/B discard remain fail-closed and identity-separated", async () => { await controlPrisma!.tenantDatabasePrincipal.update({where:{id:"principal-a1"},data:{status:"REVOKED",revokedAt:new Date()}}); adminSql(`UPDATE security.role_to_organization SET revoked_at=now() WHERE role_oid='${tenantA1}'::regrole::oid; INSERT INTO security.role_to_organization (role_oid,organization_id) VALUES ('${tenantA2}'::regrole::oid,'${orgA}');`,database); await controlPrisma!.tenantDatabasePrincipal.create({data:{id:"principal-a2",organizationId:orgA,principalName:tenantA2,credentialReference:"audit://mk/a2",generation:2,status:"ACTIVE",activatedAt:new Date()}}); entries.delete("audit://mk/a1"); const rotated=(await repository.listKpis(ctxA)).length===1 && observations.at(-1)?.identity===tenantA2; unavailable.add("audit://mk/a2"); const outage=await denies(()=>repository.listMembers(ctxA,{skip:0,take:10}),"AUTHORITY_OR_OPERATION_FAILURE"); unavailable.delete("audit://mk/a2"); const start=observations.length; const [a,b]=await Promise.all([repository.listKpis(ctxA),repository.listKpis(ctxB)]); const recent=observations.slice(start); const ao=recent.find((item)=>item.correlationId===ctxA.correlationId),bo=recent.find((item)=>item.correlationId===ctxB.correlationId); return rotated && outage && a.length===1 && b.length===1 && ao?.identity===tenantA2 && bo?.identity===tenantB1 && ao.client!==bo.client && discardCount>=checkoutCount; });
    await record("MK10", "Audit roles are non-superuser/non-BYPASSRLS; source has no global Prisma, raw GUC, DATABASE_URL fallback, and cleanup/hygiene pass", async () => { const unsafe=adminSql(`SELECT count(*) FROM pg_roles WHERE rolname IN (${roles.map((role)=>`'${role}'`).join(",")}) AND (rolsuper OR rolbypassrls)`,database); const source=["src/lib/member-kpi-repository.ts","src/app/api/members/route.ts","src/app/api/kpi/route.ts","src/app/api/members/[id]/renew/route.ts"].map((path)=>readFileSync(path,"utf8")).join("\n"); return unsafe==="0" && !/(from "@\/lib\/db"|new PrismaClient|current_setting|set_config|DATABASE_URL|organizationMemberships\[0\])/.test(source); });
    await controlPrisma.$disconnect(); controlPrisma=null; const finalCleanup=cleanup(); const payload: Record<string,unknown>={status:"PENDING",startedAt,finishedAt:new Date().toISOString(),databaseAlias:database,environment:"disposable-postgresql-audit",mandatoryIds,evidence,hardFailures:[],cleanup:finalCleanup,hygiene:{status:"PENDING"},credentialsPersisted:false,productionResourcesTouched:false,rawGucIdentityUsed:false,globalPrismaFallback:false,ownerOrBypassUsedForTenantEvidence:false}; for(const item of evidence)item.cleanupStatus=finalCleanup.ok?"PASS":"FAIL"; writeEvidence(payload); const hygiene=run("node",["scripts/w02-audit-artifact-hygiene-scan.mjs"]).status===0; payload.hygiene={status:hygiene?"PASS_AUDIT_ARTIFACT_HYGIENE_SCAN":"FAIL_AUDIT_ARTIFACT_HYGIENE_SCAN"}; const failures=evidence.filter((item)=>item.result!=="PASS").map((item)=>item.id); payload.hardFailures=failures; payload.status=!finalCleanup.ok?"FAIL_CLEANUP":!hygiene?"FAIL_HYGIENE":failures.length===0?"PASS_MEMBER_KPI_RUNTIME":"FAIL"; writeEvidence(payload); process.stdout.write(`${JSON.stringify({status:payload.status,evidenceFile,hardFailures:failures,cleanup:finalCleanup,hygiene:payload.hygiene},null,2)}\n`); process.exitCode=payload.status==="PASS_MEMBER_KPI_RUNTIME"?0:2;
  } catch { if(controlPrisma) await controlPrisma.$disconnect().catch(()=>undefined); const finalCleanup=cleanup(); writeEvidence({status:finalCleanup.ok?"FAIL_SETUP_OR_HARNESS":"FAIL_CLEANUP",startedAt,finishedAt:new Date().toISOString(),databaseAlias:database,error:"REDACTED_HARNESS_ERROR",mandatoryIds,cleanup:finalCleanup,hygiene:{status:"NOT_RUN"},credentialsPersisted:false,productionResourcesTouched:false,rawGucIdentityUsed:false,globalPrismaFallback:false,ownerOrBypassUsedForTenantEvidence:false}); process.stderr.write(`Member/KPI runtime proof failed; redacted evidence: ${evidenceFile}\n`); process.exitCode=2; }
}
void main();
